/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Mathlib.Data.PFunctor.IndRec.Basic

/-!
# Tests for inductive-recursive codes

One-step name constructors (`stepIota`, `stepSigma`, `stepPi`) build
elements of one application of the universe endofunctor `univEndo` to
a given universe, generically in the starting types and the given
universe; `rfl` tests check that their decodings are the expected
lifted starting types, dependent sums, and dependent products.

The starting types are then instantiated at a two-part family — the
natural numbers and every finite type — and the endofunctor is
iterated from the empty universe, adjoining names whose decodings mix
both starting types under dependent sums and dependent products.

The morphism action is exercised at the algebra level
(`IR.interpMorStep`), where it computes by `rfl`; `univEndoMor` itself
is generated by `IR.rec`, whose computation rule is propositional
rather than definitional, so its applications do not reduce
definitionally.

## Tags

inductive-recursive, polynomial functor, universe
-/

-- The type-valued test definitions must be `@[expose]`d so their
-- compilation types match across modules (a current compiler
-- limitation for `module`s), and `expose` is meaningful on public
-- definitions only.
@[expose] public section

open CategoryTheory IndRec

universe uK uT

section StepConstructors

variable (K : Type uK) (T : K → Type uT)
    (X : FreeCoprodCompDisc.{max uK uT, max uK uT + 1} (Type (max uK uT)))

/-- The name, in one application of `univEndo` to `X`, of the starting
type selected by `k`. -/
def stepIota (k : K) : (univEndo K T X).1 :=
  ⟨Sum.inl k, ULift.up ()⟩

-- A starting-type name decodes to the lifted starting type.
example (k : K) : (univEndo K T X).2 (stepIota K T X k) = ULift.{uK} (T k) :=
  rfl

/-- The name, in one application of `univEndo` to `X`, of the dependent
sum over the name `a` of the family of names `b`. -/
def stepSigma (a : X.1) (b : X.2 a → X.1) : (univEndo K T X).1 :=
  ⟨Sum.inr (Sum.inl PUnit.unit), fun _ ↦ a, b, ULift.up ()⟩

-- A dependent-sum name decodes to the dependent sum of the decodings.
example (a : X.1) (b : X.2 a → X.1) :
    (univEndo K T X).2 (stepSigma K T X a b) = Σ x : X.2 a, X.2 (b x) :=
  rfl

/-- The name, in one application of `univEndo` to `X`, of the dependent
product over the name `a` of the family of names `b`. -/
def stepPi (a : X.1) (b : X.2 a → X.1) : (univEndo K T X).1 :=
  ⟨Sum.inr (Sum.inr PUnit.unit), fun _ ↦ a, b, ULift.up ()⟩

-- A dependent-product name decodes to the dependent product of the
-- decodings.
example (a : X.1) (b : X.2 a → X.1) :
    (univEndo K T X).2 (stepPi K T X a b) = ((x : X.2 a) → X.2 (b x)) :=
  rfl

end StepConstructors

section NatFin

/-- The starting-type index: one tag for `Nat` and one tag per finite
type. -/
def NatFinIdx : Type := Unit ⊕ Nat

/-- The starting types: `Nat`, and `Fin n` for each `n`. -/
def NatFinTypes : NatFinIdx → Type := Sum.elim (fun _ ↦ Nat) (fun n ↦ Fin n)

/-- The universe endofunctor generated by `NatFinTypes`. -/
def natFinEndo : FreeCoprodCompDisc.Endo.{0, 1} Type :=
  univEndo NatFinIdx NatFinTypes

/-- Iteration stage zero: the empty universe. -/
def stage0 : FreeCoprodCompDisc.{0, 1} Type := ⟨PEmpty, PEmpty.elim⟩

/-- Iteration stage one: names for the starting types. -/
def stage1 : FreeCoprodCompDisc.{0, 1} Type := natFinEndo stage0

/-- Iteration stage two: fresh names for the starting types, and
dependent sums and dependent products of stage-one names. -/
def stage2 : FreeCoprodCompDisc.{0, 1} Type := natFinEndo stage1

/-- Iteration stage three: fresh names for the starting types, and
dependent sums and dependent products of stage-two names. -/
def stage3 : FreeCoprodCompDisc.{0, 1} Type := natFinEndo stage2

/-- The stage-one name of `Nat`. -/
def natName : stage1.1 := stepIota NatFinIdx NatFinTypes stage0 (Sum.inl ())

/-- The stage-one name of `Fin n`. -/
def finName (n : Nat) : stage1.1 :=
  stepIota NatFinIdx NatFinTypes stage0 (Sum.inr n)

example : stage1.2 natName = ULift Nat := rfl
example : stage1.2 (finName 5) = ULift (Fin 5) := rfl

/-- The stage-two name of `Nat` (each stage renames the starting
types). -/
def natName2 : stage2.1 := stepIota NatFinIdx NatFinTypes stage1 (Sum.inl ())

/-- The stage-one family assigning to each `n : Nat` the name of
`Fin (n + 1)`. -/
def finSuccFamily : stage1.2 natName → stage1.1 :=
  fun (n : ULift Nat) ↦ finName (n.down + 1)

/-- The stage-two name of the dependent sum `Σ n : Nat, Fin (n + 1)`. -/
def sigmaName : stage2.1 :=
  stepSigma NatFinIdx NatFinTypes stage1 natName finSuccFamily

-- The dependent-sum name decodes to the expected dependent sum, mixing
-- both starting types.
example : stage2.2 sigmaName = Σ n : ULift Nat, ULift (Fin (n.down + 1)) :=
  rfl

-- The decoded dependent sum has the expected inhabitants.
example : stage2.2 sigmaName := ⟨ULift.up (3 : Nat), ULift.up (2 : Fin 4)⟩

/-- The stage-two name of the dependent product `(n : Nat) → Fin (n + 1)`. -/
def piName : stage2.1 :=
  stepPi NatFinIdx NatFinTypes stage1 natName finSuccFamily

-- The dependent-product name decodes to the expected dependent product.
example : stage2.2 piName = ((n : ULift Nat) → ULift (Fin (n.down + 1))) :=
  rfl

-- The decoded dependent product has the expected inhabitants.
example : stage2.2 piName :=
  fun (n : ULift Nat) ↦ ULift.up (0 : Fin (n.down + 1))

/-- The stage-three name of `Σ _ : ((n : Nat) → Fin (n + 1)), Nat`: a
dependent sum over a stage-two dependent-product name. -/
def sigmaPiName : stage3.1 :=
  stepSigma NatFinIdx NatFinTypes stage2 piName (fun _ ↦ natName2)

-- Iterated formation: the stage-three decoding nests a stage-two
-- dependent product inside a dependent sum.
example : stage3.2 sigmaPiName =
    Σ _ : ((n : ULift Nat) → ULift (Fin (n.down + 1))), ULift Nat :=
  rfl

end NatFin

section MorphismAction

-- The morphism action is tested through `IR.interpMorStep` (one
-- algebra step), which computes by `rfl`; `IR.interpMor` routes
-- through `IR.rec`, whose computation rule is propositional.

/-- A domain object: one point, decoding to `Nat`. -/
def morSrc : FreeCoprodCompDisc.{0, 1} Type := ⟨Unit, fun _ ↦ Nat⟩

/-- A codomain object: two points, decoding to `Nat`. -/
def morTgt : FreeCoprodCompDisc.{0, 1} Type := ⟨Bool, fun _ ↦ Nat⟩

/-- A morphism from `morSrc` to `morTgt`: the point maps to `true`. -/
def morHom : FreeCoprodCompDisc.Hom Type morSrc morTgt :=
  ⟨fun _ ↦ true, rfl⟩

/-- The decoding assigned to each index of the sigma test code. -/
def SigmaTestDecode : ULift.{1} Bool → Type :=
  fun b ↦ if b.down then Nat else Bool

/-- The subcodes of a sigma test code over `Bool`: `iota` codes
decoding to `Nat` and `Bool`. -/
def sigmaTestSub : ULift.{1} Bool → IR.{0, 1} Type :=
  fun b ↦ IR.iota Type (SigmaTestDecode b)

/-- The sigma-case morphism action of `IR.interpMorStep` at `morHom`. -/
def sigmaTestMor :
    FreeCoprodCompDisc.Hom Type
      (IR.interpObj Type (IR.sigma Type Bool sigmaTestSub) morSrc)
      (IR.interpObj Type (IR.sigma Type Bool sigmaTestSub) morTgt) :=
  IR.interpMorStep Type (Sum.inr (Sum.inl Bool)) sigmaTestSub
    (fun b ↦ IR.interpMorIota Type (SigmaTestDecode b))
    morSrc morTgt morHom

-- The sigma action preserves the tag and the payload.
example : sigmaTestMor.1 ⟨true, ULift.up ()⟩ = ⟨true, ULift.up ()⟩ := rfl

/-- The decoding assigned to each index of the delta test code: the
decoding assigned to `true`. -/
def DeltaTestDecode : (Bool → Type) → Type :=
  fun f ↦ f true

/-- The subcodes of a delta test code over `Bool`: `iota` codes at the
index decodings. -/
def deltaTestSub : (Bool → Type) → IR.{0, 1} Type :=
  fun f ↦ IR.iota Type (DeltaTestDecode f)

/-- The delta-case morphism action of `IR.interpMorStep` at `morHom`. -/
def deltaTestMor :
    FreeCoprodCompDisc.Hom Type
      (IR.interpObj Type (IR.delta Type Bool deltaTestSub) morSrc)
      (IR.interpObj Type (IR.delta Type Bool deltaTestSub) morTgt) :=
  IR.interpMorStep Type (Sum.inr (Sum.inr Bool)) deltaTestSub
    (fun f ↦ IR.interpMorIota Type (DeltaTestDecode f))
    morSrc morTgt morHom

-- The delta action reindexes a name by postcomposition with the
-- morphism and preserves the payload.
example :
    deltaTestMor.1 ⟨fun _ ↦ (), ULift.up ()⟩ =
      ⟨fun _ ↦ true, ULift.up ()⟩ :=
  rfl

-- The image of a name decodes to the same type as the name.
example :
    (IR.interpObj Type (IR.delta Type Bool deltaTestSub) morTgt).2
        (deltaTestMor.1 ⟨fun _ ↦ (), ULift.up ()⟩) =
      Nat :=
  rfl

end MorphismAction
