/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Prototypes.FiniteChoice

/-!
# Tests for finite choice and congruence in finitely many arguments

The sum of a pair of naturals indexed by the booleans respects the equivalence relation
generated by advancing a natural by two, in each summand and so in both.

## Tags

prototype, finite choice, equivalence relation, congruence
-/

@[expose] public section

namespace GebProto.FiniteChoiceTests

/-- Two naturals are related when the second exceeds the first by two. -/
def stepTwo (n m : ℕ) : Prop := m = n + 2

/-- The sum of a pair of naturals indexed by the booleans. -/
def pairSum (g : Bool → ℕ) : ℕ := g false + g true

/-- Advancing one summand by two advances the sum by two. -/
theorem pairSum_update (g : Bool → ℕ) (i : Bool) (y : ℕ) (h : stepTwo (g i) y) :
    stepTwo (pairSum g) (pairSum (Function.update g i y)) := by
  unfold stepTwo pairSum at *
  cases i
  · rw [Function.update_self, Function.update_of_ne (by decide : true ≠ false)]
    omega
  · rw [Function.update_self, Function.update_of_ne (by decide : false ≠ true)]
    omega

/-- Summands related in each place give related sums. -/
theorem pairSum_eqvGen {g g' : Bool → ℕ} (h : ∀ i, Relation.EqvGen stepTwo (g i) (g' i)) :
    Relation.EqvGen stepTwo (pairSum g) (pairSum g') :=
  letI : FinEnum Bool := finEnumBool
  eqvGen_of_update (r := fun _ ↦ stepTwo) pairSum pairSum_update h

example : Relation.EqvGen stepTwo (pairSum fun b ↦ cond b 1 0) (pairSum fun b ↦ cond b 3 2) :=
  pairSum_eqvGen fun i ↦ by cases i <;> exact .rel _ _ rfl

end GebProto.FiniteChoiceTests

end
