/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Prototypes.Computability.Triage.Bitstrings
public import Geb.Prototypes.Computability.Oitavem.Word
public import Geb.Prototypes.RoseTree.Basic
public import Mathlib.Logic.Relation

set_option doc.verso true in
/-!
# Computation certificates for a bootstrap kernel

Certificates are rose trees with byte-sized rule tags and natural-number payloads.
Payloads use the existing bitstring rank bijection. The checker reconstructs a pair
of serialized triage expressions, using reflexivity, one reduction, symmetry, and
transitivity. Unknown tags, wrong arities, malformed expressions, nonzero payloads
on structural rules, and mismatched transitivity endpoints are rejected.

This is a computation-equality fragment, not a presentation of the free topos.
Its reduction rule follows the existing branch-first strategy; completeness for
the equivalence closure of all contextual contractions is not asserted.

## Main definitions

* {lit}`Certificate` is the finite representation of a derivation.
* {lit}`ValidClaim` expresses equality generated by contextual triage reduction.
* {lit}`infer` reconstructs the claim of a certificate.
* {lit}`check` compares that claim with the requested endpoints.

## Main statements

* {lit}`check_sound` relates every accepted certificate to the existing semantics.

## Tags

bootstrap, proof certificate, tree calculus, soundness
-/

set_option doc.verso true

@[expose] public section

namespace Geb.Bootstrap

/-- A pair of serialized expressions whose computation equality is claimed. -/
abbrev Claim := List Bool × List Bool

/-- A rule tag and payload at each node; child counts are checked by the kernel. -/
abbrev Certificate := RoseTree (UInt8 × ℕ)

/-- Both endpoints represent expressions related by contextual computation equality. -/
def ValidClaim (p : Claim) : Prop :=
  ∃ e f : Triage.Expr, e.encode = p.1 ∧ f.encode = p.2 ∧
    Relation.EqvGen Triage.Step e f

/-- Check one rule against the reconstructed claims of its children. Tags zero and one
carry a ranked expression; tags two and three carry zero and have one and two premises. -/
-- ponytail: full bit-list encodings allocate; use packed words after proving codec equivalence.
def inferNode (label : UInt8 × ℕ) (ps : List (Option Claim)) : Option Claim :=
  match label.1.toNat, label.2, ps with
  | 0, n, [] =>
    let w := Oitavem.unrank n
    if Triage.recognize w then some (w, w) else none
  | 1, n, [] =>
    let w := Oitavem.unrank n
    match Triage.reduce w with
    | .next w' => some (w, w')
    | _ => none
  | 2, 0, [some (a, b)] => some (b, a)
  | 3, 0, [some (a, b), some (c, d)] => if b == c then some (a, d) else none
  | _, _, _ => none

/-- Reconstruct a certificate's conclusion by a fold, rejecting invalid premises. -/
def infer : Certificate → Option Claim := RoseTree.elim inferNode

/-- Accept precisely a certificate reconstructing the requested pair of endpoints. -/
def check (p : Certificate) (a b : List Bool) : Bool := infer p == some (a, b)

/-- Each inference preserves the interpretation of its accepted premises. -/
theorem inferNode_sound (label : UInt8 × ℕ) (ps : List (Option Claim)) (p : Claim)
    (hps : ∀ q, some q ∈ ps → ValidClaim q) (h : inferNode label ps = some p) :
    ValidClaim p := by
  unfold inferNode at h
  split at h
  · dsimp only at h
    split at h
    · cases h
      obtain ⟨e, he⟩ := (Triage.recognize_iff _).mp (by assumption)
      exact ⟨e, e, he, he, .refl _⟩
    · cases h
  · dsimp only at h
    split at h
    · cases h
      obtain ⟨e, f, he, hf, _, hs⟩ := Triage.reduce_next_sound (by assumption)
      exact ⟨e, f, he, hf, .rel _ _ hs⟩
    · cases h
  · cases h
    obtain ⟨e, f, he, hf, hs⟩ := hps _ List.mem_cons_self
    exact ⟨f, e, hf, he, .symm _ _ hs⟩
  · split at h
    · cases h
      obtain ⟨e, f, he, hf, hs⟩ := hps _ List.mem_cons_self
      obtain ⟨g, k, hg, hk, ht⟩ := hps _ (List.mem_cons_of_mem _ List.mem_cons_self)
      have hm : f = g := Triage.Expr.encode_injective (by
        rw [hf, hg]
        exact beq_iff_eq.mp (by assumption))
      subst g
      exact ⟨e, k, he, hk, .trans _ _ _ hs ht⟩
    · cases h
  · cases h

/-- A successful fold reconstructs a semantically valid claim. -/
theorem infer_sound (t : Certificate) (p : Claim) (h : infer t = some p) :
    ValidClaim p := by
  refine RoseTree.ind (P := fun t ↦ ∀ p, infer t = some p → ValidClaim p) ?_ t p h
  intro label cs ih p hp
  apply inferNode_sound label (cs.map infer) p
  · intro q hq
    obtain ⟨c, hc, he⟩ := List.mem_map.mp hq
    exact ih c hc q he
  · simpa only [infer, RoseTree.elim_node] using hp

/-- Acceptance proves that the requested endpoints encode computation-equivalent expressions. -/
theorem check_sound (t : Certificate) (a b : List Bool) (h : check t a b = true) :
    ValidClaim (a, b) := infer_sound t (a, b) (beq_iff_eq.mp h)

end Geb.Bootstrap

end
