/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Prototypes.Definition.Presentation.Slice.Term
meta import GebMeta -- shake: keep

set_option doc.verso true in
/-!
# Equational presentations over a slice polynomial endofunctor

A presentation over a slice polynomial endofunctor {lit}`F` over {lit}`I`
({lit}`Slice.Presentation`) is a slice polynomial endofunctor {lit}`E` of equations, each with an
output sort and its variables with their input sorts, and two sides for each equation,
well-sorted terms of its output sort in its variables. Its underlying presentation
({lit}`Slice.Presentation.toPresentation`) is that of the underlying polynomial functors
({name}`Geb.Definition.Presentation`), whose witnesses and endpoints it restricts: a witness of
sort {lit}`i` is a well-sorted term of sort {lit}`i` of {lit}`Slice.sum F E`, and its endpoints,
the underlying ones, are well-sorted terms of sort {lit}`i` ({lit}`Slice.Presentation.src`).

The classes of terms of sort {lit}`i` ({lit}`Slice.Presentation.Cls`) are the coequalizer of the
two endpoint maps at {lit}`i`. The equivalence relation is generated by well-sorted witnesses
alone: a chain of the underlying presentation's witnesses may pass through terms that are not
well sorted, and so relate well-sorted terms that no chain of well-sorted witnesses relates.

An algebra of {lit}`F` over {lit}`I` satisfies the presentation when the two sides of every
equation receive equal values at every assignment of its variables lying over their sorts
({lit}`Slice.Presentation.Satisfies`). Then the two endpoints of every well-sorted witness have
equal values ({lit}`Slice.Presentation.evalS_src`), by induction on the witness through
{name}`Geb.Definition.Slice.evalS_bind`, and evaluation descends to the classes
({lit}`Slice.Presentation.lift`).

## Main definitions

* {lit}`Slice.Presentation` — equations with sorts and the two sides of each.
* {lit}`Slice.Tm`, {lit}`Slice.Presentation.Wit` — the well-sorted terms and
  witnesses of a sort.
* {lit}`Slice.Presentation.src`, {lit}`Slice.Presentation.tgt` — the endpoints of a witness.
* {lit}`Slice.Presentation.Cls`, {lit}`Slice.Presentation.cls` — the classes of a sort.
* {lit}`Slice.Presentation.Satisfies` — an algebra over {lit}`I` satisfies the equations.
* {lit}`Slice.Presentation.lift` — the value of a class.

## Main statements

* {lit}`Slice.Presentation.cls_bind_lhs` — the two sides of an equation, substituted alike, have
  one class.
* {lit}`Slice.Presentation.cls_eq_iff` — two terms of a sort have one class exactly when the
  well-sorted witnesses of that sort relate them by the equivalence relation they generate.
* {lit}`Slice.Presentation.evalS_src` — in a satisfying algebra, the endpoints of a witness have
  equal values.

## References

* {cite}`KellyPower1993`, for presentations of finitary monads by operations and equations.

## Tags

equational presentation, many-sorted algebra, slice polynomial functor, coequalizer, quotient
-/

set_option doc.verso true

@[expose] public section

namespace Geb.Definition.Slice

open PFunctor

universe uA uE uI u v

variable {I : Type uI}

/-- The well-sorted terms of sort {lit}`i`. -/
abbrev Tm (F : SlicePFunctor.{uA, u, uI, uI} I I) {Γ : Type u} (γ : Γ → I) (i : I) :
    Type (max uA u) :=
  {t : F.toPFunctor.FreeM Γ // WellSorted γ t ∧ sort γ t = i}

/-- An equational presentation over a slice polynomial endofunctor: equations with their output
sorts and the input sorts of their variables, and the two sides of each, well-sorted terms of
its output sort in its variables. -/
structure Presentation (F : SlicePFunctor.{uA, u, uI, uI} I I) :
    Type (max uA (uE + 1) (u + 1) uI) where
  /-- The equations, with their variables as directions. -/
  E : SlicePFunctor.{uE, u, uI, uI} I I
  /-- The left side of each equation. -/
  lhs : Derived F.toPFunctor E.toPFunctor
  /-- The right side of each equation. -/
  rhs : Derived F.toPFunctor E.toPFunctor
  /-- The left sides are well sorted. -/
  lhs_sorted : DerivedSorted lhs
  /-- The right sides are well sorted. -/
  rhs_sorted : DerivedSorted rhs

namespace Presentation

variable {F : SlicePFunctor.{uA, u, uI, uI} I I} (p : Presentation.{uA, uE, uI, u} F)
  {Γ : Type u} (γ : Γ → I)

/-- The presentation of the underlying polynomial functors. -/
def toPresentation : Geb.Definition.Presentation.{uA, uE, u} F.toPFunctor :=
  ⟨p.E.toPFunctor, p.lhs, p.rhs⟩

/-- The well-sorted witnesses of sort {lit}`i`. -/
abbrev Wit (i : I) : Type (max uA uE u) :=
  {w : (sum F p.E).toPFunctor.FreeM Γ // WellSorted γ w ∧ sort γ w = i}

/-- The source of a well-sorted witness is well sorted, of the witness's sort. -/
theorem wellSorted_src {w : (sum F p.E).toPFunctor.FreeM Γ} (hw : WellSorted γ w) :
    WellSorted γ (p.toPresentation.src w) ∧ sort γ (p.toPresentation.src w) = sort γ w :=
  wellSorted_expandOps (derivedSorted_handler p.lhs_sorted) w hw

/-- The target of a well-sorted witness is well sorted, of the witness's sort. -/
theorem wellSorted_tgt {w : (sum F p.E).toPFunctor.FreeM Γ} (hw : WellSorted γ w) :
    WellSorted γ (p.toPresentation.tgt w) ∧ sort γ (p.toPresentation.tgt w) = sort γ w :=
  wellSorted_expandOps (derivedSorted_handler p.rhs_sorted) w hw

/-- A well-sorted term as a witness is well sorted, of the term's sort. -/
theorem wellSorted_refl {t : F.toPFunctor.FreeM Γ} (ht : WellSorted γ t) :
    WellSorted (F := sum F p.E) γ (p.toPresentation.refl t) ∧
      sort (F := sum F p.E) γ (p.toPresentation.refl t) = sort γ t :=
  wellSorted_expandOps (derivedSorted_inlOps (E := p.E)) t ht

/-- The source of a witness of sort {lit}`i`. -/
def src {i : I} (w : p.Wit γ i) : Tm F γ i :=
  ⟨p.toPresentation.src w.1, (p.wellSorted_src γ w.2.1).1,
    (p.wellSorted_src γ w.2.1).2.trans w.2.2⟩

/-- The target of a witness of sort {lit}`i`. -/
def tgt {i : I} (w : p.Wit γ i) : Tm F γ i :=
  ⟨p.toPresentation.tgt w.1, (p.wellSorted_tgt γ w.2.1).1,
    (p.wellSorted_tgt γ w.2.1).2.trans w.2.2⟩

/-- Two terms of a sort are linked when they are the endpoints of a witness of that sort. -/
def Linked {i : I} (s t : Tm F γ i) : Prop := ∃ w, p.src γ w = s ∧ p.tgt γ w = t

/-- The classes of terms of sort {lit}`i`: the coequalizer of the two endpoint maps at
{lit}`i`. -/
abbrev Cls (i : I) : Type (max uA u) := Function.Coequalizer (p.src γ (i := i)) (p.tgt γ)

/-- The class of a term. -/
abbrev cls {i : I} (t : Tm F γ i) : p.Cls γ i := Function.Coequalizer.mk _ _ t

/-- The two endpoints of a witness have one class. -/
theorem cls_src {i : I} (w : p.Wit γ i) : p.cls γ (p.src γ w) = p.cls γ (p.tgt γ w) :=
  Function.Coequalizer.condition _ _ w

/-- Two terms of a sort have one class exactly when the witnesses of that sort relate them by
the equivalence relation they generate. -/
theorem cls_eq_iff {i : I} (s t : Tm F γ i) :
    p.cls γ s = p.cls γ t ↔ Relation.EqvGen (p.Linked γ) s t := by
  refine ⟨fun h ↦ Relation.EqvGen.mono ?_ _ _ (Quot.eqvGen_exact h),
    fun h ↦ Quot.eqvGen_sound (Relation.EqvGen.mono ?_ _ _ h)⟩
  · rintro _ _ ⟨w⟩
    exact ⟨w, rfl, rfl⟩
  · rintro _ _ ⟨w, rfl, rfl⟩
    exact ⟨w⟩

/-- The instance of an equation at a well-sorted substitution: a witness of the equation's
output sort. -/
def inst (e : p.E.A) (σ : p.E.B e → F.toPFunctor.FreeM Γ)
    (hσ : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ σ) : p.Wit γ (p.E.q e) :=
  ⟨p.toPresentation.inst e σ, fun v ↦
    ⟨(p.wellSorted_refl γ (hσ v).1).2.trans (hσ v).2, (p.wellSorted_refl γ (hσ v).1).1⟩, rfl⟩

/-- The left side of an equation, substituted by a well-sorted substitution. -/
def lhsBind (e : p.E.A) (σ : p.E.B e → F.toPFunctor.FreeM Γ)
    (hσ : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ σ) : Tm F γ (p.E.q e) :=
  ⟨(p.lhs e).bind σ, (wellSorted_bind hσ _ (p.lhs_sorted e).1).1,
    (wellSorted_bind hσ _ (p.lhs_sorted e).1).2.trans (p.lhs_sorted e).2⟩

/-- The right side of an equation, substituted by a well-sorted substitution. -/
def rhsBind (e : p.E.A) (σ : p.E.B e → F.toPFunctor.FreeM Γ)
    (hσ : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ σ) : Tm F γ (p.E.q e) :=
  ⟨(p.rhs e).bind σ, (wellSorted_bind hσ _ (p.rhs_sorted e).1).1,
    (wellSorted_bind hσ _ (p.rhs_sorted e).1).2.trans (p.rhs_sorted e).2⟩

/-- The two sides of an equation, substituted alike by a well-sorted substitution, have one
class. -/
theorem cls_bind_lhs (e : p.E.A) (σ : p.E.B e → F.toPFunctor.FreeM Γ)
    (hσ : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ σ) :
    p.cls γ (p.lhsBind γ e σ hσ) = p.cls γ (p.rhsBind γ e σ hσ) := by
  have hs : p.src γ (p.inst γ e σ hσ) = p.lhsBind γ e σ hσ :=
    Subtype.ext (p.toPresentation.src_inst e σ)
  have ht : p.tgt γ (p.inst γ e σ hσ) = p.rhsBind γ e σ hσ :=
    Subtype.ext (p.toPresentation.tgt_inst e σ)
  rw [← hs, ← ht]
  exact p.cls_src γ _

variable {A : Alg.{uA, uI, u, v} F}

/-- An algebra over {lit}`I` satisfies the presentation when the two sides of each equation
receive the same value at every assignment of its variables lying over their sorts. -/
def Satisfies (A : Alg.{uA, uI, u, v} F) : Prop :=
  ∀ (e : p.E.A) (σ : p.E.B e → A.carrier) (hσ : A.p ∘ σ = fun v ↦ p.E.r ⟨e, v⟩),
    evalS A _ σ hσ (p.lhs e) (p.lhs_sorted e).1 = evalS A _ σ hσ (p.rhs e) (p.rhs_sorted e).1

variable {γ}

/-- In an algebra satisfying the presentation, the two endpoints of every well-sorted witness
have equal values. -/
theorem evalS_src (h : p.Satisfies A) (env : Γ → A.carrier) (henv : A.p ∘ env = γ)
    (w : (sum F p.E).toPFunctor.FreeM Γ) (hw : WellSorted γ w) :
    evalS A γ env henv (p.toPresentation.src w) (p.wellSorted_src γ hw).1 =
      evalS A γ env henv (p.toPresentation.tgt w) (p.wellSorted_tgt γ hw).1 := by
  refine FreeM.rec (motive := fun w ↦ ∀ hw : WellSorted γ w,
    evalS A γ env henv (p.toPresentation.src w) (p.wellSorted_src γ hw).1 =
      evalS A γ env henv (p.toPresentation.tgt w) (p.wellSorted_tgt γ hw).1)
    (fun _ _ ↦ rfl) ?_ w hw
  intro a k ih hw
  rcases a with a | e
  · exact congrArg A.g (Subtype.ext (Sigma.ext rfl (heq_of_eq (funext fun b ↦ ih b (hw b).2))))
  · have hs : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ fun v ↦ p.toPresentation.src (k v) := fun v ↦
      ⟨(p.wellSorted_src γ (hw v).2).1, (p.wellSorted_src γ (hw v).2).2.trans (hw v).1⟩
    have ht : IsSorted (fun v ↦ p.E.r ⟨e, v⟩) γ fun v ↦ p.toPresentation.tgt (k v) := fun v ↦
      ⟨(p.wellSorted_tgt γ (hw v).2).1, (p.wellSorted_tgt γ (hw v).2).2.trans (hw v).1⟩
    exact (evalS_bind hs env henv (p.lhs e) (p.lhs_sorted e).1).trans ((h e _ _).trans
      ((evalS_congr_env _ _ _ (funext fun v ↦ ih v (hw v).2) (p.rhs e) (p.rhs_sorted e).1).trans
        (evalS_bind ht env henv (p.rhs e) (p.rhs_sorted e).1).symm))

/-- The value of a class of sort {lit}`i` in an algebra satisfying the presentation, at an
assignment of the variables lying over their sorts: the value of any term of the class. -/
def lift (h : p.Satisfies A) (env : Γ → A.carrier) (henv : A.p ∘ env = γ) (i : I) :
    p.Cls γ i → A.carrier :=
  Function.Coequalizer.desc _ _ (fun t ↦ evalS A γ env henv t.1 t.2.1)
    (funext fun w ↦ p.evalS_src h env henv w.1 w.2.1)

/-- The value of the class of a term is the value of the term. -/
@[simp] theorem lift_cls (h : p.Satisfies A) (env : Γ → A.carrier) (henv : A.p ∘ env = γ)
    {i : I} (t : Tm F γ i) : p.lift h env henv i (p.cls γ t) = evalS A γ env henv t.1 t.2.1 :=
  rfl

/-- The value of a class of sort {lit}`i` lies over {lit}`i`. -/
theorem p_lift (h : p.Satisfies A) (env : Γ → A.carrier) (henv : A.p ∘ env = γ) {i : I}
    (c : p.Cls γ i) : A.p (p.lift h env henv i c) = i :=
  Quot.ind (β := fun c ↦ A.p (p.lift h env henv i c) = i)
    (fun t ↦ (p_evalS γ env henv t.1 t.2.1).trans t.2.2) c

end Presentation

end Geb.Definition.Slice

end
