/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Mathlib.CategoryTheory.FreeCoprodCompDisc
public import Geb.Mathlib.Logic.Equiv.Basic
public import Mathlib.Data.PFunctor.Univariate.Basic

/-!
# Codes for positive inductive-recursive definitions

`IR I O` is the type of codes for inductive-recursive definitions with
input index type `I` and output index type `O`, presented as the W-type
of a polynomial functor `IR.pFunctor I O` whose shapes are the three
code constructors — constant (`iota`), dependent sum (`sigma`), and
dependent product (`delta`) — and whose directions are their subcode
arities. A code is interpreted as a functor from the free coproduct
completion of `I` to that of `O` (both treated as discrete categories,
`CategoryTheory.FreeCoprodCompDisc`, the category of families of
elements of the index type): this file constructs the object map and
morphism map of the interpretation.
It follows [GhaniNordvallForsbergMalatesta2015], Section 2
(Definitions 2.1–2.2, Theorem 2.4, and Examples 2.5–2.6), which
presents the codes of [DybjerSetzer1999] and the functorial semantics
of [DybjerSetzer2003]. The split into separate input and output index
types — generalizing the single shared index type of
[DybjerSetzer1999] and [DybjerSetzer2003] — follows Definition 3 of
[HancockMcBrideGhaniMalatestaAltenkirch2013], whose footnote observes
that the generalization allows the construction of partial fixed
points.

## Main definitions

* `IR.pFunctor` — the polynomial functor whose W-type defines codes:
  shapes `IR.Shape`, directions `IR.Direction`.
* `IR.Dest`, `IR.Dest.elim`, `IR.Dest.elimInv`, `IR.destEquiv` — the
  pattern-matched destructor for morphisms out of `IR.Obj`, its
  conversions to and from such morphisms, and the equivalence they
  form.
* `IR.DepDest`, `IR.DepDest.elim`, `IR.DepDest.elimInv`,
  `IR.depDestEquiv` — the dependent counterparts.
* `IR.objIota`, `IR.objSigma`, `IR.objDelta` — the element
  constructors of `IR.Obj`, one per shape.
* `IR`, `IR.mk` — the type of codes and its constructor.
* `IR.iota`, `IR.sigma`, `IR.delta` — the code constructors, one per
  shape.
* `IR.elim`, `IR.rec` — the eliminator and the dependent recursor,
  the latter with step arguments of type `IR.RecStep` (the `Type`
  specialization, alongside `IR.InductionStep` for `Prop`, of the
  `Sort`-valued `IR.Step`).
* `IR.interpObj`, `IR.interpMor` — the object map and morphism map of
  the interpretation of an `IR` code as a `FreeCoprodCompDisc.Map` (a
  functor between the free coproduct completions of `I` and `O`).
* `univCode`, `univEndo`, `univEndoMor` — the code of the universe
  generated by an arbitrary family of starting types and closed under
  dependent sums and dependent products, with the object and morphism
  maps of its interpretation.

## Main statements

* `IR.ext`, `IR.snd_eq_of_eq` — extensionality for codes.
* `IR.induction` — the induction principle, the recursor restricted to
  `Prop`-valued motives.

## Implementation notes

The interpretation is given by its object map (`IR.interpObj`) and
its morphism map (`IR.interpMor`); the functor laws (preservation of
identities and composition, completing Theorem 2.4 of
[GhaniNordvallForsbergMalatesta2015]) are not yet stated. Neither is
the propositional computation rule of `IR.rec`, which would
characterize `IR.interpMor` at each code constructor. The initial
algebras of the interpreted endofunctors — the universes the codes
describe, in the endofunctor case `IR I I` — are not constructed
here; the set-theoretic model of [DybjerSetzer2003] justifies their
existence using a Mahlo cardinal.

The sigma and delta arities of `IR.Shape` share the single universe
`uA`, following the single `Set` of Definition 2.1. The output index
type `O` parameterizes the `iota` shapes (a code `IR.iota I O o`
decodes to `o : O`); the input index type `I` parameterizes the
`delta` directions (a code `IR.delta I O A c` receives the decodings
of its recursive arguments as assignments `A → I`).

The whole file is exposed (`@[expose] public section`): downstream
modules, in particular the tests, rely on definitional reduction
through every definition here.

## References

* [DybjerSetzer1999]
* [DybjerSetzer2003]
* [GhaniNordvallForsbergMalatesta2015]
* [HancockMcBrideGhaniMalatestaAltenkirch2013]

## Tags

inductive-recursive, polynomial functor, W-type, universe, container
-/

@[expose] public section

universe uA uI uO

namespace IndRec

open CategoryTheory

variable (I : Type uI) (O : Type uO)

namespace IR

/-- The shape type of the polynomial functor whose W-type defines
codes for positive inductive-recursive types. -/
def Shape : Type (max (uA + 1) uO) :=
  O ⊕ Type uA ⊕ Type uA

/-- The direction type of the polynomial functor whose W-type defines
codes for positive inductive-recursive types. -/
def Direction : Shape.{uA, uO} O → Type (max uA uI) :=
  Sum.elim (fun _ ↦ PEmpty)
    (Sum.elim (fun A ↦ ULift.{uI} A) (fun A ↦ A → I))

/-- Simplification for the constant (`iota`) case of `IR.Direction`. -/
@[simp]
theorem direction_iota (o : O) : Direction.{uA, uI, uO} I O (Sum.inl o) = PEmpty := rfl

/-- Simplification for the dependent sum (`sigma`) case of
`IR.Direction`. -/
@[simp]
theorem direction_sigma (A : Type uA) :
    Direction.{uA, uI, uO} I O (Sum.inr (Sum.inl A)) = ULift.{uI} A := rfl

/-- Simplification for the dependent product (`delta`) case of
`IR.Direction`. -/
@[simp]
theorem direction_delta (A : Type uA) :
    Direction.{uA, uI, uO} I O (Sum.inr (Sum.inr A)) = (A → I) := rfl

/-- Rewrite the direction type along a shape-type equality. -/
def directionOfEq {s s' : Shape.{uA, uO} O} : s = s' → Direction I O s → Direction I O s'
  | rfl => id

/-- Elimination rule for `IR.Direction`. -/
def directionElim.{v} (V : Type v) (σ : (A : Type uA) → A → V)
    (δ : (A : Type uA) → (A → I) → V) (s : Shape O) (ds : Direction I O s) : V :=
  match s with
  | Sum.inl _ => PEmpty.elim ds
  | Sum.inr (Sum.inl (A : Type uA)) => σ A (ULift.down ds)
  | Sum.inr (Sum.inr (A : Type uA)) => δ A ds

/-- The polynomial functor whose W-type defines codes for positive
inductive-recursive types. -/
def pFunctor : PFunctor.{max (uA + 1) uO, max uA uI} :=
  ⟨Shape O, Direction I O⟩

/-- The value at `V` of the interpretation of `IR.pFunctor` as an
endofunctor on `Type`. -/
def Obj.{v} (V : Type v) : Type (max (uA + 1) uI uO v) :=
  PFunctor.Obj.{v, max (uA + 1) uO, max uA uI} (pFunctor I O) V

/-- The first component of `IR.Obj`. -/
def ObjFst : Type (max (uA + 1) uO) :=
  Shape.{uA, uO} O

/-- The second component of `IR.Obj`. -/
def ObjSnd.{v} (V : Type v) : ObjFst O → Type (max uA uI v) :=
  fun s ↦ Direction.{uA, uI, uO} I O s → V

/-- Rewrite the second component of `IR.Obj` along a shape-type
equality. -/
def objSndOfEq.{v} (V : Type v) {s s' : ObjFst.{uA, uO} O} :
    s = s' → ObjSnd I O V s → ObjSnd I O V s'
  | rfl => id

/-- The constant (`iota`) element constructor of `IR.Obj`: shape `o`,
no directions. -/
def objIota.{v} (V : Type v) (o : O) : Obj.{uA, uI, uO, v} I O V :=
  ⟨Sum.inl o, PEmpty.elim⟩

/-- The dependent sum (`sigma`) element constructor of `IR.Obj`: shape
`A`, directions assigned by `f` (through the lifted direction type
`ULift A`). -/
def objSigma.{v} (V : Type v) (A : Type uA) (f : A → V) :
    Obj.{uA, uI, uO, v} I O V :=
  ⟨Sum.inr (Sum.inl A), f ∘ ULift.down⟩

/-- The dependent product (`delta`) element constructor of `IR.Obj`:
shape `A`, directions assigned by `f`. -/
def objDelta.{v} (V : Type v) (A : Type uA) (f : (A → I) → V) :
    Obj.{uA, uI, uO, v} I O V :=
  ⟨Sum.inr (Sum.inr A), f⟩

/-- Every element of `IR.Obj` with an `iota` shape equals the
`IR.objIota` element: direction assignments out of the empty direction
type are all equal. -/
theorem objIota_eq_mk.{v} (V : Type v) (o : O)
    (ds : Direction.{uA, uI, uO} I O (Sum.inl o) → V) :
    objIota I O V o = (⟨Sum.inl o, ds⟩ : Obj.{uA, uI, uO, v} I O V) :=
  congrArg (Sigma.mk (Sum.inl o)) (funext (fun x ↦ PEmpty.elim x))

/-- A destructor for `IR.Obj` — a pattern-matched form of
elimination. -/
def Dest.{v, w} (V : Type v) (W : Type w) : Type (max (uA + 1) uI uO v w) :=
  (O → W) × ((A : Type uA) → (A → V) → W) × ((A : Type uA) → ((A → I) → V) → W)

/-- Convert `IR.Dest` to a morphism out of `IR.Obj` (an eliminator). -/
def Dest.elim.{v, w} (V : Type v) (W : Type w)
    (dest : Dest.{uA, uI, uO, v, w} I O V W) : Obj I O V → W :=
  fun ⟨s, ds⟩ ↦ match s with
  | Sum.inl o => dest.1 o
  | Sum.inr (Sum.inl (A : Type uA)) => dest.2.1 A (ds ∘ ULift.up)
  | Sum.inr (Sum.inr (A : Type uA)) => dest.2.2 A ds

/-- The inverse of `IR.Dest.elim`. -/
def Dest.elimInv.{v, w} (V : Type v) (W : Type w) (m : Obj I O V → W) :
    Dest.{uA, uI, uO, v, w} I O V W :=
  ⟨fun o ↦ m (objIota I O V o),
    fun A f ↦ m (objSigma I O V A f),
    fun A f ↦ m (objDelta I O V A f)⟩

/-- `IR.Dest.elimInv` is a left inverse of `IR.Dest.elim`. -/
theorem Dest.elimInv_elim.{v, w} (V : Type v) (W : Type w)
    (dest : Dest.{uA, uI, uO, v, w} I O V W) :
    Dest.elimInv.{uA, uI, uO, v, w} I O V W (Dest.elim.{uA, uI, uO, v, w} I O V W dest) =
      dest :=
  rfl

/-- `IR.Dest.elimInv` is a right inverse of `IR.Dest.elim`. -/
theorem Dest.elim_elimInv.{v, w} (V : Type v) (W : Type w)
    (m : Obj I O V → W) :
    Dest.elim.{uA, uI, uO, v, w} I O V W (Dest.elimInv.{uA, uI, uO, v, w} I O V W m) = m :=
  funext <| fun ⟨s, ds⟩ ↦ match s with
  | Sum.inl o => congrArg m (objIota_eq_mk.{uA, uI, uO, v} I O V o ds)
  | Sum.inr (Sum.inl _) => rfl
  | Sum.inr (Sum.inr _) => rfl

/-- `IR.Dest` is equivalent to the morphisms out of `IR.Obj`. -/
def destEquiv.{v, w} (V : Type v) (W : Type w) :
    Dest.{uA, uI, uO, v, w} I O V W ≃ (Obj I O V → W) where
  toFun := Dest.elim I O V W
  invFun := Dest.elimInv I O V W
  left_inv := Dest.elimInv_elim I O V W
  right_inv := Dest.elim_elimInv I O V W

/-- A dependent destructor for `IR.Obj` — a pattern-matched form of
elimination. -/
def DepDest.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    Type (max (uA + 1) uI uO v w) :=
  ((o : O) → W (objIota I O V o)) ×
    ((A : Type uA) → (f : A → V) → W (objSigma I O V A f)) ×
    ((A : Type uA) → (f : (A → I) → V) → W (objDelta I O V A f))

/-- Convert `IR.DepDest` to a destructor into a sigma type. -/
def sigmaDest.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    DepDest.{uA, uI, uO, v, w} I O V W →
      Dest.{uA, uI, uO, v, max (uA + 1) uI uO v w} I O V (Σ e, W e) :=
  fun dest ↦
    ⟨fun o ↦ ⟨objIota I O V o, dest.1 o⟩,
      fun A f ↦ ⟨objSigma I O V A f, dest.2.1 A f⟩,
      fun A f ↦ ⟨objDelta I O V A f, dest.2.2 A f⟩⟩

/-- Convert `IR.DepDest` to a morphism into a sigma type. -/
def sigmaElim.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    DepDest.{uA, uI, uO, v, w} I O V W → Obj I O V → Σ e, W e :=
  Dest.elim.{uA, uI, uO, v, max (uA + 1) uI uO v w} I O V (Σ e, W e) ∘
    sigmaDest.{uA, uI, uO, v, w} I O V W

/-- `IR.sigmaElim` is a section of the first projection. -/
theorem sigmaElim_fst.{v, w} (V : Type v) (W : Obj I O V → Type w)
    (dest : DepDest.{uA, uI, uO, v, w} I O V W) (e : Obj I O V) :
    (sigmaElim I O V W dest e).1 = e :=
  match e with
  | ⟨s, ds⟩ => match s with
    | Sum.inl o => objIota_eq_mk.{uA, uI, uO, v} I O V o ds
    | Sum.inr (Sum.inl _) => rfl
    | Sum.inr (Sum.inr _) => rfl

/-- Convert `IR.DepDest` to a dependent eliminator for `IR.Obj`. -/
def DepDest.elim.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    DepDest.{uA, uI, uO, v, w} I O V W → (e : Obj I O V) → W e :=
  fun dest ↦
    sigmaFstSectionElim (sigmaElim I O V W dest) (sigmaElim_fst I O V W dest)

/-- The inverse of `IR.DepDest.elim`. -/
def DepDest.elimInv.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    ((e : Obj I O V) → W e) → DepDest.{uA, uI, uO, v, w} I O V W :=
  fun m ↦
    ⟨fun o ↦ m (objIota I O V o),
      fun A f ↦ m (objSigma I O V A f),
      fun A f ↦ m (objDelta I O V A f)⟩

/-- `IR.DepDest.elimInv` is a left inverse of `IR.DepDest.elim`. -/
theorem DepDest.elimInv_elim.{v, w} (V : Type v) (W : Obj I O V → Type w)
    (dest : DepDest.{uA, uI, uO, v, w} I O V W) :
    DepDest.elimInv.{uA, uI, uO, v, w} I O V W
      (DepDest.elim.{uA, uI, uO, v, w} I O V W dest) = dest :=
  rfl

/-- `IR.DepDest.elimInv` is a right inverse of `IR.DepDest.elim`. -/
theorem DepDest.elim_elimInv.{v, w} (V : Type v) (W : Obj I O V → Type w)
    (m : (e : Obj I O V) → W e) :
    DepDest.elim.{uA, uI, uO, v, w} I O V W
      (DepDest.elimInv.{uA, uI, uO, v, w} I O V W m) = m :=
  funext <| fun ⟨s, ds⟩ ↦ match s with
  | Sum.inl o => objIota_eq_mk.{uA, uI, uO, v} I O V o ds ▸ rfl
  | Sum.inr (Sum.inl _) => rfl
  | Sum.inr (Sum.inr _) => rfl

/-- `IR.DepDest` is equivalent to the dependent eliminators of
`IR.Obj`. -/
def depDestEquiv.{v, w} (V : Type v) (W : Obj I O V → Type w) :
    DepDest.{uA, uI, uO, v, w} I O V W ≃ ((e : Obj I O V) → W e) where
  toFun := DepDest.elim I O V W
  invFun := DepDest.elimInv I O V W
  left_inv := DepDest.elimInv_elim I O V W
  right_inv := DepDest.elim_elimInv I O V W

/-- A pattern-matched form of an algebra of `IR.pFunctor`. -/
def Alg.{v} (V : Type v) : Type (max (uA + 1) uI uO v) :=
  Dest.{uA, uI, uO, v, v} I O V V

/-- Convert `IR.Alg` to the morphism form of an algebra of
`IR.pFunctor`. -/
def Alg.toHom.{v} (V : Type v) (alg : Alg.{uA, uI, uO, v} I O V) : Obj I O V → V :=
  Dest.elim.{uA, uI, uO, v, v} I O V V alg

end IR

/-- The type of codes for positive inductive-recursive definitions:
the W-type of `IR.pFunctor`. -/
def IR : Type (max (uA + 1) uI uO) :=
  PFunctor.W.{max (uA + 1) uO, max uA uI} (IR.pFunctor I O)

namespace IR

/-- The constructor for `IR`. -/
def mk (s : Shape O) (d : Direction I O s → IR I O) : IR I O :=
  WType.mk.{max (uA + 1) uO, max uA uI} s d

/-- The constant (`iota`) code: no subcodes; its interpretation is the
constant functor at the object with one name decoding to `o`. -/
def iota (o : O) : IR.{uA, uI, uO} I O :=
  mk I O (Sum.inl o) PEmpty.elim

/-- The dependent sum (`sigma`) code: subcodes `c` indexed by `A`
(through the lifted direction type `ULift A`); its interpretation is
the pointwise indexed coproduct over `A` of the interpretations of the
subcodes. -/
def sigma (A : Type uA) (c : ULift.{uI} A → IR.{uA, uI, uO} I O) : IR I O :=
  mk I O (Sum.inr (Sum.inl A)) c

/-- The dependent product (`delta`) code: subcodes `c` indexed by the
assignments of decodings to `A`; its interpretation takes recursive
arguments indexed by `A` and passes their decodings to `c`. -/
def delta (A : Type uA) (c : (A → I) → IR.{uA, uI, uO} I O) : IR I O :=
  mk I O (Sum.inr (Sum.inr A)) c

/-- Congruence for `IR.mk` in the direction assignment. -/
theorem mk_congr (s : Shape O) {ds ds' : Direction I O s → IR I O} :
    ds = ds' → mk.{uA, uI, uO} I O s ds = mk.{uA, uI, uO} I O s ds'
  | rfl => rfl

/-- The motive of the proof of `IR.ext`. -/
def ExtMotive (s : Shape.{uA, uO} O) (d : Direction I O s → IR I O)
    (s' : Shape O) (eq1 : s = s') : Prop :=
  ∀ d' : Direction I O s' → IR I O, d = d' ∘ directionOfEq I O eq1 → mk I O s d = mk I O s' d'

/-- Extensionality for `IR` (equality is determined by equality of
shapes and pointwise equality of directions). -/
theorem ext {ir ir' : IR.{uA, uI, uO} I O} (eq1 : ir.1 = ir'.1)
    (eq2 : ir.2 = ir'.2 ∘ directionOfEq I O eq1) : ir = ir' :=
  match ir, ir' with
  | ⟨s, d⟩, ⟨_, d'⟩ =>
      Eq.rec (motive := ExtMotive I O s d) (fun _ ↦ mk_congr I O s) eq1 d' eq2

/-- The converse of `IR.ext`: an equality in `IR` determines a
pointwise equality of directions (transported along the shape equality
induced by the first projection). -/
theorem snd_eq_of_eq {ir ir' : IR.{uA, uI, uO} I O} :
    (eq : ir = ir') → ir.2 = ir'.2 ∘ directionOfEq I O (congrArg (fun t ↦ t.1) eq)
  | rfl => rfl

/-- The eliminator (the algebra morphism from the initial algebra) for
`IR`, taking the algebra in morphism form. -/
def elim.{v} (V : Type v) (alg : Obj.{uA, uI, uO, v} I O V → V) : IR I O → V :=
  WType.elim.{max (uA + 1) uO, max uA uI, v} V alg

/-- The eliminator for `IR`, taking the algebra in the `IR.Alg` form. -/
def elimAlg.{v} (V : Type v) (alg : Alg.{uA, uI, uO, v} I O V) : IR I O → V :=
  elim I O V (Alg.toHom I O V alg)

/-- The type of the step argument of `IR`'s recursors at a
`Sort`-valued motive: from a shape, a subcode assignment, and results
for the subcodes, produce the result for the constructed code. The
result sort (an `imax` expression) is left to inference; the
specializations `IR.RecStep` and `IR.InductionStep` carry the explicit
ascriptions. -/
def Step.{v} (motive : IR.{uA, uI, uO} I O → Sort v) :=
  (a : Shape O) → (f : Direction I O a → IR I O) →
  ((d : Direction I O a) → motive (f d)) → motive (mk I O a f)

/-- The step argument type at a `Type`-valued motive (for `IR.rec`,
`IR.sigmaRec`, and their companions). -/
def RecStep.{v} (motive : IR.{uA, uI, uO} I O → Type v) :
    Type (max (uA + 1) uI uO v) :=
  Step I O motive

/-- The step argument type at a `Prop`-valued motive (for `IR.induction`). -/
def InductionStep (motive : IR.{uA, uI, uO} I O → Prop) : Prop :=
  Step I O motive

/-- The induction principle — the recursor restricted to `Prop`-valued
motives. (The compiler does not generate code for `WType.rec`
applications, so `WType.rec` is used only here, where propositions
need no code.) -/
theorem induction (motive : IR I O → Prop) :
    InductionStep.{uA, uI, uO} I O motive → ∀ t : IR I O, motive t :=
  WType.rec.{0, max (uA + 1) uO, max uA uI}
    (α := Shape O) (β := Direction I O) (motive := motive)

/-- The `IR.pFunctor` algebra over a sigma type generated by a
recursor step. -/
def sigmaRecAlg.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) :
    Obj I O (Σ e, motive e) → Σ e, motive e :=
  fun ⟨s, f⟩ ↦
    ⟨mk I O s (Sigma.fst ∘ f), mk' s (Sigma.fst ∘ f) (fun d ↦ (f d).2)⟩

/-- `IR.sigmaRecAlg` preserves the shape component. -/
theorem sigmaRecAlg_fst_fst.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) (t : Obj I O (Σ e, motive e)) :
    (sigmaRecAlg I O motive mk' t).1.1 = t.1 :=
  rfl

/-- `IR.sigmaRecAlg` preserves the direction component. -/
theorem sigmaRecAlg_fst_snd.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) (t : Obj I O (Σ e, motive e)) :
    (sigmaRecAlg I O motive mk' t).1.2 = Sigma.fst ∘ t.2 :=
  rfl

/-- The recursor's auxiliary fold into a sigma type. -/
def sigmaRec.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) : IR I O → Σ e, motive e :=
  elim I O (Σ e, motive e) (sigmaRecAlg I O motive mk')

/-- The inductive step of the proof that `IR.sigmaRec` is a section of
the first projection. -/
theorem sigmaRec_fst_step.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) :
    InductionStep.{uA, uI, uO} I O (fun t ↦ (sigmaRec I O motive mk' t).1 = t) :=
  fun _ _ ih ↦ ext I O rfl (funext ih)

/-- `IR.sigmaRec` is a section of the first projection. -/
theorem sigmaRec_fst.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) :
    ∀ t : IR I O, (sigmaRec I O motive mk' t).1 = t :=
  induction I O (motive := fun t ↦ (sigmaRec I O motive mk' t).1 = t)
    (sigmaRec_fst_step I O motive mk')

/-- The shape component of `IR.sigmaRec` agrees with the shape
component of the argument. -/
theorem sigmaRec_fst_fst.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) (t : IR I O) :
    (sigmaRec I O motive mk' t).1.1 = t.1 :=
  match t with
  | ⟨_, _⟩ => rfl

/-- The direction component of `IR.sigmaRec` agrees with the direction
component of the argument, transported along `IR.sigmaRec_fst_fst`. -/
theorem sigmaRec_fst_snd.{v} (motive : IR I O → Type v)
    (mk' : RecStep.{uA, uI, uO, v} I O motive) (t : IR I O) :
    (sigmaRec I O motive mk' t).1.2 =
      t.2 ∘ directionOfEq I O (sigmaRec_fst_fst I O motive mk' t) :=
  snd_eq_of_eq I O (sigmaRec_fst I O motive mk' t)

/-- The recursor — the dependent eliminator for `IR`. -/
def rec.{v} {motive : IR I O → Type v} (mk' : RecStep.{uA, uI, uO, v} I O motive) :
    (t : IR I O) → motive t :=
  sigmaFstSectionElim (sigmaRec I O motive mk') (sigmaRec_fst I O motive mk')

end IR

namespace IR

/-- The constant (`iota`) case of the interpretation of an `IR` code
as a `FreeCoprodCompDisc.Map`: the constant object map at the
singleton family decoding to `o`. -/
def interpObjIota (o : O) : FreeCoprodCompDisc.Map.{uA, uI, uO} I O :=
  fun _ ↦ ⟨ULift Unit, fun _ ↦ o⟩

/-- The dependent sum (`sigma`) case of the interpretation of an `IR`
code as a `FreeCoprodCompDisc.Map`: the pointwise indexed coproduct
over `A` of the interpretations `α` of the subcodes. -/
def interpObjSigma (A : Type uA)
    (α : A → FreeCoprodCompDisc.Map.{uA, uI, uO} I O) :
    FreeCoprodCompDisc.Map.{uA, uI, uO} I O :=
  fun X ↦ FreeCoprodCompDisc.coprod.{uA, uO, uA} O A (fun a ↦ α a X)

/-- The dependent product (`delta`) case of the interpretation of an
`IR` code as a `FreeCoprodCompDisc.Map`: at an object `X`, the
indexed coproduct over `A → X.1` of the interpretations `α` of the
subcodes at the directions induced by `X`. -/
def interpObjDelta (A : Type uA)
    (α : (A → I) → FreeCoprodCompDisc.Map.{uA, uI, uO} I O) :
    FreeCoprodCompDisc.Map.{uA, uI, uO} I O :=
  fun X ↦
    FreeCoprodCompDisc.coprod.{uA, uO, uA} O (A → X.1) (fun g ↦ α (X.2 ∘ g) X)

/-- The algebra which computes one step of the interpretation of an
`IR` code as a `FreeCoprodCompDisc.Map`. -/
def interpObjAlg :
    Alg.{uA, uI, uO, max (uA + 1) uI uO} I O
      (FreeCoprodCompDisc.Map.{uA, uI, uO} I O) :=
  ⟨interpObjIota I O, interpObjSigma I O, interpObjDelta I O⟩

/-- The object map of the interpretation of an `IR` code as a
`FreeCoprodCompDisc.Map`. -/
def interpObj : IR.{uA, uI, uO} I O → FreeCoprodCompDisc.Map.{uA, uI, uO} I O :=
  elimAlg I O (FreeCoprodCompDisc.Map.{uA, uI, uO} I O) (interpObjAlg I O)

/-- The signature of the morphism map accompanying `IR.interpObj`. -/
def MorMapSig (ir : IR.{uA, uI, uO} I O) : Type (max (uA + 1) uI) :=
  FreeCoprodCompDisc.MapMor I O (interpObj I O ir)

/-- The morphism-map component of the constant (`iota`) interpretation
`IR.interpObjIota`: every morphism maps to the identity. -/
def interpMorIota (o : O) :
    FreeCoprodCompDisc.MapMor I O (interpObjIota.{uA, uI, uO} I O o) :=
  fun _ _ _ ↦ ⟨id, rfl⟩

/-- The morphism-map component of the dependent sum (`sigma`)
interpretation `IR.interpObjSigma`: the indexed coproduct of the
componentwise morphism maps `μ`. -/
def interpMorSigma (A : Type uA)
    (α : A → FreeCoprodCompDisc.Map.{uA, uI, uO} I O)
    (μ : (a : A) → FreeCoprodCompDisc.MapMor I O (α a)) :
    FreeCoprodCompDisc.MapMor I O (interpObjSigma I O A α) :=
  fun X Y h ↦
    FreeCoprodCompDisc.coprodMor O A A id
      (fun a ↦ α a X)
      (fun a ↦ α a Y)
      (fun a ↦ μ a X Y h)

/-- The morphism-map component of the dependent product (`delta`)
interpretation `IR.interpObjDelta`: reindex along postcomposition with
the morphism, transporting each componentwise morphism map `μ` along
the morphism's commutation equality. -/
def interpMorDelta (A : Type uA)
    (α : (A → I) → FreeCoprodCompDisc.Map.{uA, uI, uO} I O)
    (μ : (f : A → I) → FreeCoprodCompDisc.MapMor I O (α f)) :
    FreeCoprodCompDisc.MapMor I O (interpObjDelta I O A α) :=
  fun X Y h ↦
    FreeCoprodCompDisc.coprodMor O (A → X.1) (A → Y.1) (fun g ↦ h.1 ∘ g)
      (fun g ↦ α (X.2 ∘ g) X)
      (fun g ↦ α (Y.2 ∘ g) Y)
      (fun g ↦
        FreeCoprodCompDisc.homOfEq O
          (congrArg (fun t ↦ α (t ∘ g) Y) h.2.symm)
          (μ (X.2 ∘ g) X Y h))

/-- The step argument to the recursor which generates the morphism map
of the interpretation of an `IR` code as a `FreeCoprodCompDisc.Map`
(the object map is `IR.interpObj`). -/
def interpMorStep : RecStep.{uA, uI, uO, max (uA + 1) uI} I O (MorMapSig I O) :=
  fun s c m ↦ match s with
  | Sum.inl o => interpMorIota I O o
  | Sum.inr (Sum.inl A) =>
      interpMorSigma I O A
        (fun a ↦ interpObj I O (c (ULift.up a)))
        (fun a ↦ m (ULift.up a))
  | Sum.inr (Sum.inr A) =>
      interpMorDelta I O A
        (fun f ↦ interpObj I O (c f))
        m

/-- The morphism map of the interpretation of an `IR` code as a
`FreeCoprodCompDisc.Map` (the object map is `IR.interpObj`). -/
def interpMor (ir : IR.{uA, uI, uO} I O) : MorMapSig I O ir :=
  rec I O (interpMorStep I O) ir

end IR

section Universes

/-! ### Universes closed under dependent sums and products

The code of the universe generated by an arbitrary family of starting
types and closed under dependent sums and dependent products,
combining Examples 2.5 and 2.6 of
[GhaniNordvallForsbergMalatesta2015]: the coproduct of one `iota`
code per starting type (in place of the examples' single `iota` code
for the natural numbers), one dependent-sum former, and one
dependent-product former. The universe is an endofunctor example
(`IR I I`), so the input and output index types coincide.
-/

universe uK uT

/-- The binder-former subcode shared by `univSigma` and `univPi`: one
recursive argument (the type bound by the binder), then recursive
arguments indexed by its decoding (the family of types under the
binder), decoding to `former` applied to the decodings. -/
def univBinder.{v} (former : (X : Type v) → (X → Type v) → Type v) :
    IR.{v, v + 1, v + 1} (Type v) (Type v) :=
  IR.delta (Type v) (Type v) PUnit.{v + 1} (fun f ↦
    IR.delta (Type v) (Type v) (f PUnit.unit) (fun q ↦
      IR.iota (Type v) (Type v) (former (f PUnit.unit) q)))

/-- The dependent-sum-former subcode of a universe code. -/
def univSigma.{v} : IR.{v, v + 1, v + 1} (Type v) (Type v) :=
  univBinder (fun X q ↦ Σ x : X, q x)

/-- The dependent-product-former subcode of a universe code. -/
def univPi.{v} : IR.{v, v + 1, v + 1} (Type v) (Type v) :=
  univBinder (fun X q ↦ (x : X) → q x)

variable (K : Type uK) (T : K → Type uT)

/-- The starting-type subcode of a universe code: an `iota` code
decoding to the lifted starting type selected by `k`. -/
def univIota (k : K) :
    IR.{max uK uT, max uK uT + 1, max uK uT + 1}
      (Type (max uK uT)) (Type (max uK uT)) :=
  IR.iota (Type (max uK uT)) (Type (max uK uT)) (ULift.{uK} (T k))

/-- The constructors of the universe generated by a family of starting
types: one nullary constructor per starting type, a dependent-sum
former, and a dependent-product former. -/
def UnivConstructor : Type (max uK uT) :=
  K ⊕ PUnit.{max uK uT + 1} ⊕ PUnit.{max uK uT + 1}

/-- The subcode of the universe code selected by each constructor. -/
def univConstructorCode :
    UnivConstructor.{uK, uT} K →
      IR.{max uK uT, max uK uT + 1, max uK uT + 1}
        (Type (max uK uT)) (Type (max uK uT)) :=
  Sum.elim (univIota K T)
    (Sum.elim (fun _ ↦ univSigma.{max uK uT}) (fun _ ↦ univPi.{max uK uT}))

/-- The code of the universe generated by the starting types `T`: the
coproduct, over `UnivConstructor`, of the subcodes. The universe
itself — containing the (lifted) starting types and closed under
dependent sums and dependent products — is the initial algebra of the
code's interpretation; this file provides the code and the
interpretation, not the initial algebra. -/
def univCode :
    IR.{max uK uT, max uK uT + 1, max uK uT + 1}
      (Type (max uK uT)) (Type (max uK uT)) :=
  IR.sigma (Type (max uK uT)) (Type (max uK uT)) (UnivConstructor.{uK, uT} K)
    (fun i ↦ univConstructorCode K T i.down)

/-- The object map of the interpretation of `univCode`. -/
def univEndo :
    FreeCoprodCompDisc.Endo.{max uK uT, max uK uT + 1} (Type (max uK uT)) :=
  IR.interpObj (Type (max uK uT)) (Type (max uK uT)) (univCode K T)

/-- The morphism map of the interpretation of `univCode` (the object
map is `univEndo`). -/
def univEndoMor :
    FreeCoprodCompDisc.EndoMor (Type (max uK uT)) (univEndo K T) :=
  IR.interpMor (Type (max uK uT)) (Type (max uK uT)) (univCode K T)

end Universes

end IndRec
