/-
Copyright (c) 2026 The geb-mathlib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The geb-mathlib contributors
-/
module

public import Mathlib.Data.PFunctor.Univariate.Basic

/-!
# Codes for positive inductive-recursive definitions

`IR D` is the type of codes for inductive-recursive definitions with
output type `D`, presented as the W-type of a polynomial functor
`IRpf D` whose shapes are the three code constructors — constant
(`iota`), dependent sum (`sigma`), and dependent product (`delta`) —
and whose directions are their subcode arities. A code is interpreted
on the free coproduct completion of `D` treated as a discrete category
(the category of families of elements of `D`): this file constructs
the object map and morphism map of the interpretation. It follows
[GhaniNordvallForsbergMalatesta2015], Section 2 (Definitions 2.1–2.2,
Theorem 2.4, and Examples 2.5–2.6), which presents the codes of
[DybjerSetzer1999] and the functorial semantics of
[DybjerSetzer2003].

## Main definitions

* `IRpf` — the polynomial functor whose W-type defines codes: shapes
  `IRshape`, directions `IRdir`.
* `IRdest`, `IRelim`, `IRelimInv` — the pattern-matched destructor for
  morphisms out of `IRobj` and its conversions to and from such
  morphisms.
* `IRdepDest`, `IRdepElim`, `IRdepElimInv` — the dependent
  counterparts.
* `IR`, `IRmk` — the type of codes and its constructor.
* `IRiota`, `IRsigma`, `IRdelta` — the code constructors, one per
  shape.
* `IRcata`, `IRrec` — the catamorphism and the dependent recursor.
* `FreeCoprodCompDisc`, `FreeCoprodCompDisc.Hom`,
  `freeCoprodCompDiscCopr`, `freeCoprodCompDiscCoprMor` — the free
  coproduct completion of `D` treated as a discrete category: objects,
  morphisms, indexed coproducts, and the coproducts' functorial
  action.
* `IRinterpObj`, `IRinterpMor` — the object map and morphism map of
  the interpretation of a code on `FreeCoprodCompDisc`.
* `univCode`, `univEndo`, `univEndoMor` — the code of the universe
  generated by an arbitrary family of starting types and closed under
  dependent sums and dependent products, with the object and morphism
  maps of its interpretation.

## Main statements

* `IRelimIso` — `IRdest` is isomorphic to the morphisms out of
  `IRobj`.
* `IRdepElimIso` — `IRdepDest` is isomorphic to the dependent
  eliminators of `IRobj`.
* `IRmkExt`, `IRmkExtInv` — extensionality for codes.

## Implementation notes

The interpretation is given by its object map (`IRinterpObj`) and its
morphism map (`IRinterpMor`); the functor laws (preservation of
identities and composition, completing Theorem 2.4 of
[GhaniNordvallForsbergMalatesta2015]) are not yet stated. Neither is
the propositional computation rule of `IRrec`, which would
characterize `IRinterpMor` at each code constructor. The initial
algebras of the interpreted endofunctors — the universes the codes
describe — are not constructed here; the set-theoretic model of
[DybjerSetzer2003] justifies their existence using a Mahlo cardinal.

## References

* [DybjerSetzer1999]
* [DybjerSetzer2003]
* [GhaniNordvallForsbergMalatesta2015]

## Tags

inductive-recursive, polynomial functor, W-type, universe, container
-/

@[expose]
public section

universe uA uD

namespace IndRec

variable (D : Type uD)

set_option linter.checkUnivs false in
/-- The shape type of the polynomial functor whose W-type
defines codes for positive inductive-recursive types. -/
def IRshape : Type (max (uA + 1) uD) :=
  D ⊕ Type uA ⊕ Type uA

/-- The direction type of the polynomial functor whose W-type
defines codes for positive inductive-recursive types. -/
def IRdir : IRshape D → Type (max uA uD)
  | Sum.inl _ => PEmpty
  | Sum.inr (Sum.inl (A : Type uA)) => ULift A
  | Sum.inr (Sum.inr (A : Type uA)) => A → D

/-- Simplification for constant (`iota`) case of `IRdir`. -/
@[simp]
lemma IRdirL (d : D) : IRdir.{uA, uD} D (Sum.inl d) = PEmpty := rfl

/-- Simplification for dependent sum (`sigma`) case of `IRdir`. -/
@[simp]
lemma IRdirRL (A : Type uA) : IRdir D (Sum.inr (Sum.inl A)) = ULift A := rfl

/-- Simplification for dependent product (`delta`) case of `IRdir`. -/
@[simp]
lemma IRdirRR (A : Type uA) : IRdir D (Sum.inr (Sum.inr A)) = (A → D) := rfl

/-- Rewrite the direction type given shape-type equality. -/
def IRdirRW {s s' : IRshape.{uA, uD} D} : s = s' → IRdir D s → IRdir D s'
  | rfl => id

/-- Elimination rule for `IRdir`. -/
def IRdirElim.{v} (V : Type v)
  (σ : (A : Type uA) → A → V)
  (δ : (A : Type uA) → (A → D) → V)
  (s : IRshape D) (ds : IRdir D s) : V :=
    match s with
      | Sum.inl _ => PEmpty.elim ds
      | Sum.inr (Sum.inl (A : Type uA)) => σ A (ULift.down ds)
      | Sum.inr (Sum.inr (A : Type uA)) => δ A ds

/-- The polynomial functor whose W-type defines codes for
positive inductive-recursive types. -/
def IRpf : PFunctor.{max (uA + 1) uD, max uA uD} :=
  ⟨IRshape D, IRdir D⟩

/-- The interpretation of `IRpf` into endofunctors on `Type`. -/
def IRobj.{v} (V : Type v) : Type (max (uA + 1) uD v) :=
  PFunctor.Obj.{v, max (uA + 1) uD, max uA uD} (IRpf D) V

/-- The first component of `IRobj`. -/
def IRobj1 : Type (max (uA + 1) uD) :=
  IRshape.{uA, uD} D

/-- The second component of `IRobj`. -/
def IRobj2.{v} (V : Type v) : IRobj1 D → Type (max uA uD v) :=
  fun s => IRdir.{uA, uD} D s → V

/-- Rewrite the second component of `IRobj` given shape-type equality. -/
def IRobj2RW.{v} (V : Type v) {s s' : IRobj1.{uA, uD} D} :
  s = s' → IRobj2 D V s → IRobj2 D V s'
    | rfl => id

/-- A destructor for `IRpf V` -- a pattern-matched form of elimination. -/
def IRdest.{v, w} (V : Type v) (W : Type w) : Type (max (uA + 1) uD v w) :=
  (D → W) × ((A : Type uA) → (A → V) → W) × ((A : Type uA) → ((A → D) → V) → W)

/-- Convert `IRdest` to a morphism out of `IRpf V` (an eliminator). -/
def IRelim.{v, w} (V : Type v) (W : Type w)
  (dest : IRdest.{uA, uD, v, w} D V W) :
    IRobj D V → W :=
      fun ⟨s, ds⟩ => match s with
        | Sum.inl d => dest.1 d
        | Sum.inr (Sum.inl (A : Type uA)) => dest.2.1 A (ds ∘ ULift.up)
        | Sum.inr (Sum.inr (A : Type uA)) => dest.2.2 A ds

/-- The inverse of `IRelim`. -/
def IRelimInv.{v, w} (V : Type v) (W : Type w)
  (m : IRobj D V → W) :
    IRdest.{uA, uD, v, w} D V W :=
      ⟨ fun d => m ⟨Sum.inl d, PEmpty.elim⟩,
        fun A f => m ⟨Sum.inr (Sum.inl A), f ∘ ULift.down⟩,
        fun A f => m ⟨Sum.inr (Sum.inr A), f⟩ ⟩

/-- `IRelimInv` is a left-inverse of `IRelim`. -/
lemma IRelimLeftInv.{v, w} (V : Type v) (W : Type w)
  (dest : IRdest.{uA, uD, v, w} D V W) :
    IRelimInv.{uA, uD, v, w} D V W (IRelim.{uA, uD, v, w} D V W dest) = dest :=
      match dest with | ⟨_, _, _⟩ => rfl

/-- `IRelimInv` is a right-inverse of `IRelim`. -/
lemma IRelimRightInv.{v, w} (V : Type v) (W : Type w)
  (m : IRobj D V → W) :
    IRelim.{uA, uD, v, w} D V W (IRelimInv.{uA, uD, v, w} D V W m) = m :=
      funext <| fun e => match e with | ⟨s, ds⟩ => match s with
        | Sum.inl _ =>
            Eq.rec rfl (funext (fun x => PEmpty.elim x) : PEmpty.elim = ds)
        | Sum.inr (Sum.inl _) =>
            rfl
        | Sum.inr (Sum.inr _) =>
            rfl

/-- `IRdest` is isomorphic to the set of morphisms out of `IRobj`. -/
def IRelimIso.{v, w} (V : Type v) (W : Type w) :
  IRdest.{uA, uD, v, w} D V W ≃ (IRobj D V → W) :=
  {
    toFun := IRelim D V W
    invFun := IRelimInv D V W
    left_inv := IRelimLeftInv D V W
    right_inv := IRelimRightInv D V W
  }

/-- A dependent destructor for `IRpf V` -- a pattern-matched form of
elimination. -/
def IRdepDest.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  Type (max (uA + 1) uD v w) :=
    ((d : D) → W ⟨Sum.inl d, PEmpty.elim⟩) ×
    ((A : Type uA) → (f : A → V) → W ⟨Sum.inr (Sum.inl A), f ∘ ULift.down⟩) ×
    ((A : Type uA) → (f : (A → D) → V) → W ⟨Sum.inr (Sum.inr A), f⟩)

/-- Convert `IRdepDest` to a destructor into a sigma type. -/
def IRsigmaDest.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  IRdepDest.{uA, uD, v, w} D V W →
  IRdest.{uA, uD, v, max (uA + 1) uD v w} D V (Σ e, W e) :=
    fun dest => ⟨
      fun d => ⟨⟨Sum.inl d, PEmpty.elim⟩, dest.1 d⟩,
      fun A f => ⟨⟨Sum.inr (Sum.inl A), f ∘ ULift.down⟩, dest.2.1 A f⟩,
      fun A f => ⟨⟨Sum.inr (Sum.inr A), f⟩, dest.2.2 A f⟩
    ⟩

/-- Convert `IRdepDest` to a morphism into a sigma type. -/
def IRsigmaElim.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  IRdepDest.{uA, uD, v, w} D V W → IRobj D V → Σ e, W e :=
    IRelim.{uA, uD, v, max (uA + 1) uD v w} D V (Σ e, W e) ∘
    IRsigmaDest.{uA, uD, v, w} D V W

/-- `IRsigmaElim` is a section of the first projection. -/
lemma IRsigmaElimSect.{v, w} (V : Type v) (W : IRobj D V → Type w)
  (dest : IRdepDest.{uA, uD, v, w} D V W) (e : IRobj D V) :
    (IRsigmaElim D V W dest e).1 = e :=
      match e with
        | ⟨s, ds⟩ => match s with
          | Sum.inl _ =>
            Eq.rec rfl (funext (fun x => PEmpty.elim x) : PEmpty.elim = ds)
          | Sum.inr (Sum.inl _) => rfl
          | Sum.inr (Sum.inr _) => rfl

/-- Convert `IRdepDest` to a dependent eliminator for `IRobj V`. -/
def IRdepElim.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  IRdepDest.{uA, uD, v, w} D V W → Π e, W e :=
    fun dest e =>
      Eq.ndrec (IRsigmaElim D V W dest e).2 (IRsigmaElimSect D V W dest e)

/-- The inverse of `IRdepElim`. -/
def IRdepElimInv.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  (Π e, W e) → IRdepDest.{uA, uD, v, w} D V W :=
    fun m => ⟨
      fun d => m ⟨Sum.inl d, PEmpty.elim⟩,
      fun A f => m ⟨Sum.inr (Sum.inl A), f ∘ ULift.down⟩,
      fun A f => m ⟨Sum.inr (Sum.inr A), f⟩
    ⟩

/-- `IRdepElimInv` is a left-inverse of `IRdepElim`. -/
lemma IRdepElimLeftInv.{v, w} (V : Type v) (W : IRobj D V → Type w)
  (dest : IRdepDest.{uA, uD, v, w} D V W) :
    IRdepElimInv.{uA, uD, v, w} D V W (IRdepElim.{uA, uD, v, w} D V W dest) =
    dest :=
      match dest with | ⟨_, _, _⟩ => rfl

/-- `IRdepElimInv` is a right-inverse of `IRdepElim`. -/
lemma IRdepElimRightInv.{v, w} (V : Type v) (W : IRobj D V → Type w)
  (m : Π e, W e) :
    IRdepElim.{uA, uD, v, w} D V W (IRdepElimInv.{uA, uD, v, w} D V W m) = m :=
      funext <| fun e => match e with | ⟨s, ds⟩ => match s with
        | Sum.inl _ =>
            Eq.rec rfl (funext (fun x => PEmpty.elim x) : PEmpty.elim = ds)
        | Sum.inr (Sum.inl _) =>
            rfl
        | Sum.inr (Sum.inr _) =>
            rfl

/-- `IRdepDest` is isomorphic to the dependent eliminators of `IRobj`. -/
def IRdepElimIso.{v, w} (V : Type v) (W : IRobj D V → Type w) :
  IRdepDest.{uA, uD, v, w} D V W ≃ (Π e, W e) :=
  {
    toFun := IRdepElim D V W
    invFun := IRdepElimInv D V W
    left_inv := IRdepElimLeftInv D V W
    right_inv := IRdepElimRightInv D V W
  }

/-- A pattern-matched form of an algebra of `IRpf`. -/
def IRalg.{v} (V : Type v) : Type (max (uA + 1) uD v) :=
  IRdest.{uA, uD, v, v} D V V

/-- Convert `IRalg` to a category-theoretic algebra of `IRpf`. -/
def IRcatAlg.{v} (V : Type v) (alg : IRalg.{uA, uD, v} D V) :
  IRobj D V → V :=
    IRelim.{uA, uD, v, v} D V V alg

/-- The polynomial functor which defines codes for
positive inductive-recursive types. -/
def IR : Type (max (uA + 1) uD) :=
  PFunctor.W.{max (uA + 1) uD, max uA uD} (IRpf D)

/-- The constructor for `IR`. -/
def IRmk (s : IRshape D) (d : IRdir D s → IR D) : IR D :=
  WType.mk.{max (uA + 1) uD, max uA uD} s d

/-- The constant (`iota`) code: no subcodes; its interpretation is the
constant functor at the object with one direction decoding to `d`. -/
def IRiota (d : D) : IR.{uA, uD} D :=
  IRmk D (Sum.inl d) PEmpty.elim

/-- The dependent sum (`sigma`) code: subcodes `c` indexed by `A`
(through the lifted direction type `ULift A`); its interpretation is
the pointwise indexed coproduct over `A` of the interpretations of the
subcodes. -/
def IRsigma (A : Type uA) (c : ULift.{uD} A → IR.{uA, uD} D) : IR D :=
  IRmk D (Sum.inr (Sum.inl A)) c

/-- The dependent product (`delta`) code: subcodes `c` indexed by the
assignments of decodings to `A`; its interpretation takes recursive
arguments indexed by `A` and passes their decodings to `c`. -/
def IRdelta (A : Type uA) (c : (A → D) → IR.{uA, uD} D) : IR D :=
  IRmk D (Sum.inr (Sum.inr A)) c

/-- Extensionality for `IRmk`s with the same shape. -/
lemma IRmkExtDir (s : IRshape D) {ds ds' : IRdir D s → IR D} :
  ds = ds' → IRmk.{uA, uD} D s ds = IRmk.{uA, uD} D s ds'
    | rfl => rfl

/-- The motive of the proof of extensionality for `IRmk`. -/
def IRmkExtStep
  (s : IRshape D) (d : IRdir D s → IR D) (s' : IRshape D) (eq1 : s = s') :
    Prop :=
      ∀ d' : (IRdir D s' → IR D),
        ((d = d' ∘ IRdirRW D eq1) → (IRmk D s d = IRmk D s' d'))

/-- Extensionality for `IRmk` (equality is determined by
equality of shape and pointwise equality of directions). -/
lemma IRmkExt {ir ir' : IR.{uA, uD} D} (eq1 : ir.1 = ir'.1)
  (eq2 : ir.2 = ir'.2 ∘ IRdirRW D eq1) :
  ir = ir' :=
    match ir, ir' with
      | ⟨s, d⟩, ⟨_, d'⟩ =>
          Eq.rec (motive := IRmkExtStep D s d)
            (fun _ => IRmkExtDir D s) eq1 d' eq2

/-- The converse of `IRmkExt`: an equality in `IR` determines a
pointwise equality of directions (transported along the shape
equality induced by the first projection). -/
lemma IRmkExtInv {ir ir' : IR.{uA, uD} D} :
  (eq : ir = ir') → ir.2 = ir'.2 ∘ IRdirRW D (congrArg (fun t => t.1) eq)
    | rfl => rfl

/-- The catamorphism (the unique algebra morphism out of the initial
object) for `IR`, using the category-theoretic form of an algebra. -/
def IRcataCat.{v} (V : Type v) (alg : IRobj.{uA, uD, v} D V → V) : IR D → V :=
  WType.elim.{max (uA + 1) uD, max uA uD, v} V alg

/-- The catamorphism (the unique algebra morphism out of the initial
object) for `IR`, using the convenience `IRalg` form of an algebra. -/
def IRcata.{v} (V : Type v) (alg : IRalg.{uA, uD, v} D V) : IR D → V :=
  IRcataCat D V (IRcatAlg D V alg)

/-- The induction principle -- the recursor restricted to `Prop`-valued
motives. (The compiler does not generate code for `WType.rec`
applications, so `WType.rec` is used only here, where propositions
need no code.) -/
theorem IRind (motive : IR D → Prop) :
  ((a : IRshape D) → (f : IRdir D a → IR D) →
   ((d : IRdir D a) → motive (f d)) →
   motive (IRmk.{uA, uD} D a f)) →
  Π (t : IR D), motive t :=
    WType.rec.{0, max (uA + 1) uD, max uA uD}
      (α := IRshape D) (β := IRdir D)
      (motive := motive)

/-- The `IRpf` algebra over a sigma type generated by a dependent eliminator. -/
def IRsigmaCataAlg.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f)) :
  IRobj D (Σ e, motive e) → Σ e, motive e :=
    (fun ⟨s, f⟩ =>
      ⟨IRmk D s (Sigma.fst ∘ f),
       mk s (Sigma.fst ∘ f) (fun d => (f d).2)⟩)

/-- `IRsigmaCataAlg` preserves the first projection. -/
lemma IRsigmaCataAlg1.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f))
  (t : IRobj D (Σ e, motive e)) :
    (IRsigmaCataAlg D motive mk t).1.1 = t.1 :=
  rfl

/-- `IRsigmaCataAlg` preserves the second projection. -/
lemma IRsigmaCataAlg2.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f))
  (t : IRobj D (Σ e, motive e)) :
    (IRsigmaCataAlg D motive mk t).1.2 = Sigma.fst ∘ t.2 :=
  rfl

/-- `IR`'s catamorphism on a sigma type. -/
def IRsigmaCata.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f)) :
  IR D → Σ e, motive e :=
    IRcataCat D (Σ e, motive e) (IRsigmaCataAlg D motive mk)

/-- The inductive step of the proof that `IRsigmaCata`
is a section of the first projection. -/
lemma IRsigmaCataIndStep.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (ds : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (ds d)) →
    motive (IRmk.{uA, uD} D a ds)) :
  ∀ (s : IRshape D) (ds : IRdir D s → IR D),
    (∀ (d : IRdir D s), (IRsigmaCata D motive mk (ds d)).1 = ds d) →
      (IRsigmaCata D motive mk (IRmk D s ds)).1 = IRmk D s ds :=
  fun _ _ ih => IRmkExt D rfl (funext ih)

/-- `IRSigmaCata` is a section of the first projection. -/
lemma IRsigmaCataSect.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f)) :
  (t : IR D) → (IRsigmaCata D motive mk t).1 = t :=
    IRind D
      (motive := fun t => (IRsigmaCata D motive mk t).1 = t)
      (IRsigmaCataIndStep D motive mk)

/-- The first projection of `IRSigmaCata` is a section of the
first projection of the first projection. -/
lemma IRsigmaCataSect1.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f))
  (t : IR D) :
    (IRsigmaCata D motive mk t).1.1 = t.1 :=
  match t with
    | ⟨_, _⟩ => rfl

/-- The second projection of `IRSigmaCata` is a section of the
second projection of the first projection. -/
lemma IRsigmaCataSect2.{v} (motive : IR D → Type v)
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f))
  (t : IR D) :
    (IRsigmaCata D motive mk t).1.2 =
      t.2 ∘ IRdirRW D (IRsigmaCataSect1 D motive mk t) :=
  IRmkExtInv D (IRsigmaCataSect D motive mk t)

/-- The recursor -- the dependent catamorphism for `IR`. -/
def IRrec.{v} {motive : IR D → Type v}
  (mk :
    (a : IRshape D) → (f : IRdir D a → IR D) →
    ((d : IRdir D a) → motive (f d)) →
    motive (IRmk.{uA, uD} D a f)) :
  Π t, motive t :=
    fun t =>
      Eq.ndrec (IRsigmaCata D motive mk t).2 (IRsigmaCataSect D motive mk t)

/-- The free coproduct completion of `D` treated as a discrete
category. -/
def FreeCoprodCompDisc : Type (max (uA + 1) uD) :=
  Σ (A : Type uA), A → D

/-- The (object-map components of) endofunctors on `FreeCoprodCompDisc`. -/
def FreeCoprodCompDiscEndo : Type (max (uA + 1) uD) :=
  FreeCoprodCompDisc.{uA, uD} D → FreeCoprodCompDisc.{uA, uD} D

/-- The morphisms of the free coproduct completion of `D` treated as a
discrete category. -/
def FreeCoprodCompDisc.Hom
  (X Y : FreeCoprodCompDisc.{uA, uD} D) : Type uA :=
    {h : X.1 → Y.1 // Y.2 ∘ h = X.2}

/-- Rewrite the codomain of a `FreeCoprodCompDisc.Hom` along an
equality of objects. -/
def FreeCoprodCompDisc.HomRW {X Y Y' : FreeCoprodCompDisc.{uA, uD} D} :
  Y = Y' → FreeCoprodCompDisc.Hom D X Y → FreeCoprodCompDisc.Hom D X Y'
    | rfl => id

/-- The morphism-map component over an object map on
`FreeCoprodCompDisc`. -/
def FreeCoprodCompDiscEndoMor (F : FreeCoprodCompDiscEndo D) :
  Type (max (uA + 1) uD) :=
    ∀ (X Y : FreeCoprodCompDisc.{uA, uD} D),
      FreeCoprodCompDisc.Hom D X Y → FreeCoprodCompDisc.Hom D (F X) (F Y)

/-- The indexed coproduct in the free coproduct completion
of `D` treated as a discrete category. -/
def freeCoprodCompDiscCopr.{uI} (I : Type uI)
  (fi : I → FreeCoprodCompDisc.{uA, uD} D) :
    FreeCoprodCompDisc.{max uA uI} D :=
      ⟨(Σ i : I, (fi i).1), fun ⟨i, s⟩ => (fi i).2 s⟩

/-- The functorial action of `freeCoprodCompDiscCopr` on morphisms:
a reindexing function together with a componentwise family of
morphisms induces a morphism of indexed coproducts. -/
def freeCoprodCompDiscCoprMor.{uI} (I J : Type uI) (r : I → J)
  (fi : I → FreeCoprodCompDisc.{uA, uD} D)
  (gj : J → FreeCoprodCompDisc.{uA, uD} D)
  (hom : (i : I) → FreeCoprodCompDisc.Hom D (fi i) (gj (r i))) :
    FreeCoprodCompDisc.Hom D
      (freeCoprodCompDiscCopr D I fi)
      (freeCoprodCompDiscCopr D J gj) :=
  ⟨fun ⟨i, x⟩ => ⟨r i, (hom i).1 x⟩,
   funext (fun ⟨i, x⟩ => congrFun (hom i).2 x)⟩

/-- The constant (`iota`) case of the interpretation of an IR code on
`FreeCoprodCompDisc`: the constant object map at the one-direction
object over `d`. -/
def irInterpObjIota (d : D) : FreeCoprodCompDiscEndo.{uA, uD} D :=
  fun _ => ⟨ULift Unit, fun (ULift.up ()) => d⟩

/-- The dependent sum (`sigma`) case of the interpretation of an IR code
on `FreeCoprodCompDisc`: the pointwise indexed coproduct over `A` of
the interpretations `α` of the subcodes. -/
def irInterpObjSigma (A : Type uA)
  (α : A → FreeCoprodCompDiscEndo.{uA, uD} D) :
    FreeCoprodCompDiscEndo.{uA, uD} D :=
  fun X => freeCoprodCompDiscCopr.{uA} D A (fun a => α a X)

/-- The dependent product (`delta`) case of the interpretation of an IR
code on `FreeCoprodCompDisc`: at an object `X`, the indexed coproduct
over `A → X` of the interpretations `α` of the subcodes at the
directions induced by `X`. -/
def irInterpObjDelta (A : Type uA)
  (α : (A → D) → FreeCoprodCompDiscEndo.{uA, uD} D) :
    FreeCoprodCompDiscEndo.{uA, uD} D :=
  fun X => freeCoprodCompDiscCopr.{uA} D (A → X.1) (fun g => α (X.2 ∘ g) X)

/-- The algebra which computes one step of the interpretation
of an IR code on `FreeCoprodCompDisc`. -/
def irInterpObjDest :
  IRalg.{uA, uD, max (uA + 1) uD} D (FreeCoprodCompDiscEndo.{uA, uD} D) :=
  ⟨irInterpObjIota D, irInterpObjSigma D, irInterpObjDelta D⟩

/-- The object map of the interpretation of an IR code on
`FreeCoprodCompDisc`. -/
def IRinterpObj :
  IR.{uA, uD} D → FreeCoprodCompDiscEndo.{uA, uD} D :=
    IRcata D (FreeCoprodCompDiscEndo D) (irInterpObjDest D)

/-- The signature of the morphism-map component of `IRinterpObj`. -/
def IRmorMapSig (ir : IR.{uA, uD} D) : Type (max (uA + 1) uD) :=
  FreeCoprodCompDiscEndoMor D (IRinterpObj D ir)

/-- The morphism-map component of the constant (`iota`) interpretation
`irInterpObjIota`: every morphism maps to the identity. -/
def irInterpMorIota (d : D) :
  FreeCoprodCompDiscEndoMor D (irInterpObjIota.{uA, uD} D d) :=
    fun _ _ _ => ⟨id, rfl⟩

/-- The morphism-map component of the dependent sum (`sigma`)
interpretation `irInterpObjSigma`: the indexed coproduct of the
componentwise morphism maps `μ`. -/
def irInterpMorSigma (A : Type uA)
  (α : A → FreeCoprodCompDiscEndo.{uA, uD} D)
  (μ : (a : A) → FreeCoprodCompDiscEndoMor D (α a)) :
    FreeCoprodCompDiscEndoMor D (irInterpObjSigma D A α) :=
  fun X Y h =>
    freeCoprodCompDiscCoprMor D A A id
      (fun a => α a X)
      (fun a => α a Y)
      (fun a => μ a X Y h)

/-- The morphism-map component of the dependent product (`delta`)
interpretation `irInterpObjDelta`: reindex along postcomposition with
the morphism, transporting each componentwise morphism map `μ` along
the morphism's commutation equality. -/
def irInterpMorDelta (A : Type uA)
  (α : (A → D) → FreeCoprodCompDiscEndo.{uA, uD} D)
  (μ : (f : A → D) → FreeCoprodCompDiscEndoMor D (α f)) :
    FreeCoprodCompDiscEndoMor D (irInterpObjDelta D A α) :=
  fun X Y h =>
    freeCoprodCompDiscCoprMor D (A → X.1) (A → Y.1) (fun g => h.1 ∘ g)
      (fun g => α (X.2 ∘ g) X)
      (fun g => α (Y.2 ∘ g) Y)
      (fun g =>
        FreeCoprodCompDisc.HomRW D
          (congrArg (fun t => α (t ∘ g) Y) h.2.symm)
          (μ (X.2 ∘ g) X Y h))

/-- The step argument to the recursor which generates the morphism map
of the interpretation of an IR code on `FreeCoprodCompDisc` (the
object map is `IRinterpObj`). -/
def IRinterpMorMk (s : IRshape D) (c : IRdir D s → IR D)
  (m : (d : IRdir D s) → IRmorMapSig D (c d)) :
    IRmorMapSig D (IRmk.{uA, uD} D s c) :=
  match s with
    | Sum.inl d => irInterpMorIota D d
    | Sum.inr (Sum.inl A) =>
        irInterpMorSigma D A
          (fun a => IRinterpObj D (c (ULift.up a)))
          (fun a => m (ULift.up a))
    | Sum.inr (Sum.inr A) =>
        irInterpMorDelta D A
          (fun f => IRinterpObj D (c f))
          (fun f => m f)

/-- The morphism map of the interpretation of an IR code on
`FreeCoprodCompDisc` (the object map is `IRinterpObj`). -/
def IRinterpMor
  (ir : IR.{uA, uD} D) : IRmorMapSig D ir :=
    IRrec D (IRinterpMorMk D) ir

section Universes

/-! ### Universes closed under dependent sums and products

The code of the universe generated by an arbitrary family of starting
types and closed under dependent sums and dependent products,
combining Examples 2.5 and 2.6 of
[GhaniNordvallForsbergMalatesta2015]: the coproduct of one `iota`
code per starting type (in place of the examples' single `iota` code
for the natural numbers), one dependent-sum former, and one
dependent-product former.
-/

universe uK uT

/-- The binder-former subcode shared by `univSigma` and `univPi`: one
recursive argument (the type bound by the binder), then recursive
arguments indexed by its decoding (the family of types under the
binder), decoding to `former` applied to the decodings. -/
def univBinder.{v} (former : (X : Type v) → (X → Type v) → Type v) :
  IR.{v, v + 1} (Type v) :=
    IRdelta (Type v) PUnit.{v + 1} (fun f =>
      IRdelta (Type v) (f PUnit.unit) (fun q =>
        IRiota (Type v) (former (f PUnit.unit) q)))

/-- The dependent-sum-former subcode of a universe code. -/
def univSigma.{v} : IR.{v, v + 1} (Type v) :=
  univBinder (fun X q => Σ x : X, q x)

/-- The dependent-product-former subcode of a universe code. -/
def univPi.{v} : IR.{v, v + 1} (Type v) :=
  univBinder (fun X q => (x : X) → q x)

variable (K : Type uK) (T : K → Type uT)

/-- The starting-type subcode of a universe code: an `iota` code
decoding to the lifted starting type selected by `k`. -/
def univIota (k : ULift.{uT} K) :
  IR.{max uK uT, max uK uT + 1} (Type (max uK uT)) :=
    IRiota (Type (max uK uT)) (ULift.{uK} (T k.down))

/-- The constructors of the universe generated by a family of starting
types: one nullary constructor per starting type, a dependent-sum
former, and a dependent-product former. -/
def UnivConstructor : Type (max uK uT) :=
  ULift.{uT} K ⊕ PUnit.{max uK uT + 1} ⊕ PUnit.{max uK uT + 1}

/-- The subcode of the universe code selected by each constructor. -/
def univConstructorCode :
  UnivConstructor.{uK, uT} K →
  IR.{max uK uT, max uK uT + 1} (Type (max uK uT))
    | Sum.inl k => univIota K T k
    | Sum.inr (Sum.inl _) => univSigma.{max uK uT}
    | Sum.inr (Sum.inr _) => univPi.{max uK uT}

/-- The code of the universe generated by the starting types `T`: the
coproduct, over `UnivConstructor`, of the subcodes. The universe
itself — containing the (lifted) starting types and closed under
dependent sums and dependent products — is the initial algebra of the
code's interpretation; this file provides the code and the
interpretation, not the initial algebra. -/
def univCode : IR.{max uK uT, max uK uT + 1} (Type (max uK uT)) :=
  IRsigma (Type (max uK uT)) (UnivConstructor.{uK, uT} K)
    (fun i => univConstructorCode K T i.down)

/-- The object map of the interpretation of `univCode`. -/
def univEndo :
  FreeCoprodCompDiscEndo.{max uK uT, max uK uT + 1} (Type (max uK uT)) :=
    IRinterpObj (Type (max uK uT)) (univCode K T)

/-- The morphism map of the interpretation of `univCode` (the object
map is `univEndo`). -/
def univEndoMor :
  FreeCoprodCompDiscEndoMor (Type (max uK uT)) (univEndo K T) :=
    IRinterpMor (Type (max uK uT)) (univCode K T)

end Universes

end IndRec
