/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Mathlib.Data.PFunctor.Presheaf.W
public import Mathlib.CategoryTheory.Category.Preorder
public import Mathlib.Order.Fin.Basic
public import Mathlib.Data.Fintype.Basic
public import Mathlib.Tactic.NormNum

/-!
# Prototype: the dependent-type universe as a presheaf over the walking arrow

Throwaway exploration, not upstream-eligible content. This is a Lean port of
the `IRCode`/`IRdecode` example of the Idris-2 file
`src/LanguageDef/Test/PolyIndTypesTest.idr` — the universe closed under
dependent sums and dependent products — in the inductive-inductive
(arrow) formulation of that file, on top of the presheaf inductive-inductive
types of `Geb.Mathlib.Data.PFunctor.Presheaf.W` (the W-types of presheaf
polynomial endofunctors), with the walking arrow as the underlying category.

## The construction

The walking arrow is `Fin 2` as a preorder (the unique non-identity morphism
`0 ⟶ 1`). A presheaf on it is a pair of types with a map, so the presheaf
initial algebra of an endofunctor `F : PresheafPFunctor (Fin 2) (Fin 2)` is a
pair of mutually-defined types together with a fibration — the presheaf
inductive-inductive reading of an inductive-recursive definition: one fibre
plays the role of the data type and the other the role of the decoding, with
the restriction map as the decoder.

`univPsh K` is the endofunctor of the Idris example: the shapes are the
constructors — the starting-type codes `iota k` (`k : K`), the dependent-sum
code `sigma`, the dependent-product code `pi`, and the two term shapes
`termSigma`, `termPi` — and the directions are their recursive fields: no
fields for `iota`, the bound code for `sigma`/`pi`, and for the terms the
code together with a payload. Every shape and direction is a finite type
(the `sigma`/`pi` code directions are a point and the term directions are two
points).

The W-type `univW K := (univPsh K).W` is a presheaf over the walking arrow:
`Codes := (univW K).obj ⟨0⟩` is the type of codes, `Terms := (univW K).obj
⟨1⟩` the type of terms, and `fib : Terms → Codes` — the restriction map of
the presheaf along `0 ⟶ 1` — the decoding of a term into its code. A term
`termSigma p d` decodes to the `sigma` code at `p`, discarding the payload
`d`; dually `termPi p d` decodes to the `pi` code at `p`. The fibre of `fib`
over a code — the type of its terms — is therefore the payload type: over a
`sigma` or `pi` code it is (isomorphic to) the codes themselves, and over a
starting-type code it is empty.

## Relationship to the Idris-2 formulation

The Idris-2 file defines the same universe twice: once by explicit
induction-recursion (`IRCode`, `IRdecode` — the family formulation, which the
Lean port `Geb.Mathlib.Data.PFunctor.IndRec.Universes` follows) and once
inductively-inductively over arrows (`IRCode'`, `IRTerm`, `IRfib` — the arrow
formulation, a presheaf over the walking arrow, whose domain is the terms and
whose codomain the codes). This module follows the arrow formulation. Two
deviations are forced by the W-type machinery, and both are recorded here for
the review this prototype is intended for:

1. In the Idris-2 arrow formulation a code constructor carries its recursive
   data in its *shape*: `IRCsigma' u v` is a node whose constructor argument
   is the pair `(u, v)` with `u : IRCode'` and `v : IRfib u → IRCode'`. A
   W-type of a polynomial functor has a *fixed* shape type, so the data of a
   code cannot live in its shape; it lives in its children. Here the bound
   code `u` is a child, and the family `v` — a function, and so not a
   well-founded tree — is dropped, the term payload taking its place. The
   dependent-sum and dependent-product formers are consequently *binary*:
   `sigma (u, v)` with `v : Fib u → Code` is not representable; the code
   former at `u` is.

2. In the Idris-2 formulation the terms' payloads are elements of the
   decodings, which may be arbitrary types. A W-type's children are trees, so
   a leaf payload cannot be carried; the payload here is itself a code.

Both deviations make the types *smaller* than the Idris-2 types: every code
and term is a well-founded tree built from finite shapes and directions, and
the decoding of a code — the fibre of `fib` — is a subtype of the terms, not
an arbitrary type. What is preserved is the shape of the example: a universe
generated by starting types, closed under dependent sums and products, whose
terms decode to their codes by the walking-arrow fibration, obtained as the
presheaf initial algebra rather than by explicit induction-recursion.

## Main definitions

* `waHom` — the unique non-identity morphism `0 ⟶ 1` of the walking arrow.
* `univShape` / `univDir` / `univR` / `univQ` — the shapes (the constructor
  tags), directions (the recursive fields), the direction-input map, and the
  shape-output map of `univPsh`.
* `univPsh` — the presheaf polynomial endofunctor over the walking arrow.
* `univW` — its W-type, a presheaf over the walking arrow.
* `Codes` / `Terms` / `fib` — the two fibres and the fibration.
* `univIota` / `univSigma` / `univPi` — the code constructors.
* `univTermSigma` / `univTermPi` — the term constructors.

## Main statements

* `univShapeRestr_over` — the restricted shape lies over the target index.
* `univDirection_empty` — every shape has no directions over `1`; all
  recursion is over the code fibre.
* `univPshLaws` — the seven functor laws of `univPsh`; the whole construction
  is `Classical.choice`-free, depending only on `propext` and `Quot.sound`.
* The decoding theorems — `fib (univTermSigma p d) = univSigma p` and the
  fibre statement `fib_eq_iff` — go through the root-restriction
  `wRestrTree` of the presheaf W-type, whose computation is too deep for this
  prototype; they are deferred to the review below ("Decoding").

## Tags

prototype, inductive-inductive, presheaf, walking arrow, W-type, universe,
dependent sum, dependent product
-/

@[expose] public section

open CategoryTheory

universe uK

namespace PresheafIRUniv

/-- The unique non-identity morphism of the walking arrow (`Fin 2` as a
preorder), `0 ⟶ 1`. -/
def waHom : (0 : Fin 2) ⟶ (1 : Fin 2) :=
  ULift.up (PLift.up (by decide))

/-! ## The presheaf endofunctor -/

/-- The shapes of `univPsh`: the starting-type code `iota k` for each
`k : K`, the dependent-sum code `sigma`, the dependent-product code `pi`,
and the two term shapes `termSigma`, `termPi`. -/
inductive univShape (K : Type uK) : Type uK where
  | iota (k : K)
  | sigma
  | pi
  | termSigma
  | termPi

/-- The directions of `univPsh`: none for `iota`; the bound code (a point)
for `sigma` and `pi`; and the code-and-payload pair (two points) for the two
term shapes. -/
def univDir (K : Type uK) : univShape K → Type 0
  | .iota _ => PEmpty
  | .sigma => PUnit
  | .pi => PUnit
  | .termSigma => PUnit ⊕ PUnit
  | .termPi => PUnit ⊕ PUnit

/-- The direction-input map: every direction lies over the code fibre `0`,
so the recursion of the W-type runs through the codes. -/
def univR (K : Type uK) : (Σ a : univShape K, univDir K a) → Fin 2 :=
  fun _ => 0

/-- The shape-output map: `iota`, `sigma`, and `pi` are codes (fibre `0`);
`termSigma` and `termPi` are terms (fibre `1`). -/
def univQ (K : Type uK) : univShape K → Fin 2
  | .iota _ => 0
  | .sigma => 0
  | .pi => 0
  | .termSigma => 1
  | .termPi => 1

/-- The slice polynomial functor underlying `univPsh`. -/
def univSlice (K : Type uK) : SlicePFunctor.{uK, 0, 0, 0} (Fin 2) (Fin 2) :=
  { toPFunctor := ⟨univShape K, univDir K⟩
    r := univR K
    q := univQ K }

/-- Every shape has no directions over `1`: all recursion is over the code
fibre, which is what makes the W-type's hereditary naturality over the single
non-identity morphism vacuous at every node. -/
theorem univDirection_empty (K : Type uK) (a : univShape K) :
    IsEmpty (SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor a
      (1 : Fin 2)) := by
  exact IsEmpty.mk fun d => by
    have h := d.2
    change (0 : Fin 2) = 1 at h
    omega

/-- The direction-restriction of `univPsh`: morphisms into `0` are
identities, so the restriction is the identity on the directions over `0`;
there are no directions over `1` to restrict. -/
def univDirectionRestr (K : Type uK) (a : univShape K) (i i' : Fin 2)
    (_f : i' ⟶ i) (d : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor a i) :
    SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor a i' := by
  match i, i' with
  | 0, 0 => exact d
  | 0, 1 =>
      exfalso
      have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom _f
      omega
  | 1, 0 => exact (univDirection_empty K a).elim d
  | 1, 1 => exact (univDirection_empty K a).elim d

/-- The shape-restriction of `univPsh` to a target index `t`: the code
shapes are fixed, and the term shapes are sent to the code shape of the same
former (`termSigma` to `sigma`, `termPi` to `pi`). -/
def univRestrShape (K : Type uK) (a : univShape K) (t : Fin 2) : univShape K :=
  match a, t with
  | .termSigma, 0 => .sigma
  | .termPi, 0 => .pi
  | _, _ => a

/-- The restricted shape lies over the target index. -/
theorem univShapeRestr_over (K : Type uK) (a : univShape K) (t : Fin 2)
    (ht : t ≤ univQ K a) : univQ K (univRestrShape K a t) = t := by
  cases a with
  | iota k =>
      change t ≤ (0 : Fin 2) at ht
      have ht0 : t = (0 : Fin 2) := by omega
      subst ht0
      rfl
  | sigma =>
      change t ≤ (0 : Fin 2) at ht
      have ht0 : t = (0 : Fin 2) := by omega
      subst ht0
      rfl
  | pi =>
      change t ≤ (0 : Fin 2) at ht
      have ht0 : t = (0 : Fin 2) := by omega
      subst ht0
      rfl
  | termSigma =>
      unfold univRestrShape univQ
      by_cases ht0 : t = (0 : Fin 2)
      · subst ht0
        rfl
      · have ht1 : t = (1 : Fin 2) := by omega
        subst ht1
        rfl
  | termPi =>
      unfold univRestrShape univQ
      by_cases ht0 : t = (0 : Fin 2)
      · subst ht0
        rfl
      · have ht1 : t = (1 : Fin 2) := by omega
        subst ht1
        rfl

/-- The shape-restriction of `univPsh`. -/
def univShapeRestr (K : Type uK) ⦃j j' : Fin 2⦄ (g : j' ⟶ j)
    (s : SlicePFunctor.Shape (univSlice K) j) : SlicePFunctor.Shape (univSlice K) j' :=
  ⟨univRestrShape K s.1 j', univShapeRestr_over K s.1 j' (by
    have hs : univQ K s.1 = j := s.2
    rw [hs]
    exact leOfHom g)⟩

/-- The raw direction map of the reindexing: on the code shapes the identity,
and on the term shapes the code component (`Sum.inl`) when restricting along
`0 ⟶ 1`, the identity otherwise. -/
def univReindexDir (K : Type uK) (a : univShape K) (t : Fin 2) :
    univDir K (univRestrShape K a t) → univDir K a :=
  match a, t with
  | .iota _, _ => fun b => PEmpty.elim b
  | .sigma, _ => fun b => b
  | .pi, _ => fun b => b
  | .termSigma, 0 => fun b => Sum.inl b
  | .termSigma, 1 => fun b => b
  | .termPi, 0 => fun b => Sum.inr b
  | .termPi, 1 => fun b => b

/-- The arity reindexing of `univPsh` along a walking-arrow morphism. -/
def univReindex (K : Type uK) ⦃j j' : Fin 2⦄ (g : j' ⟶ j)
    (a : SlicePFunctor.Shape (univSlice K) j) ⦃i : Fin 2⦄
    (d : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
      (univShapeRestr K g a).1 i) :
    SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor a.1 i := by
  match i with
  | 0 => exact ⟨univReindexDir K a.1 j' d.1, rfl⟩
  | 1 => exact (univDirection_empty K (univShapeRestr K g a).1).elim d

/-- The operations of the presheaf polynomial endofunctor of the universe. -/
def univPshData (K : Type uK) : PresheafPFunctorData.{0, 0, uK, 0, 0, 0}
    (Fin 2) (Fin 2) :=
  { toPFunctor := ⟨univShape K, univDir K⟩
    r := univR K
    q := univQ K
    directionRestr := univDirectionRestr K
    shapeRestr := univShapeRestr K
    reindex := univReindex K }

/-- The identity law for `shapeRestr`, as a standalone theorem. -/
theorem univShapeRestr_id_thm (K : Type uK) : (univPshData K).ShapeRestrId := by
  intro j
  funext s
  refine Subtype.ext ?_
  change univRestrShape K s.1 j = s.1
  obtain ⟨a, ha⟩ := s
  cases a with
  | iota k => rfl
  | sigma => rfl
  | pi => rfl
  | termSigma =>
      have hq : (univPshData K).q .termSigma = j := by exact ha
      have hj : j = (1 : Fin 2) := by
        change j = (univPshData K).q .termSigma
        exact hq.symm
      subst hj
      rfl
  | termPi =>
      have hq : (univPshData K).q .termPi = j := by exact ha
      have hj : j = (1 : Fin 2) := by
        change j = (univPshData K).q .termPi
        exact hq.symm
      subst hj
      rfl

/-- The composition law for `shapeRestr`, as a standalone theorem. -/
theorem univShapeRestr_comp_thm (K : Type uK) : (univPshData K).ShapeRestrComp := by
  intro j j' j'' g h
  funext s
  refine Subtype.ext ?_
  change univRestrShape K s.1 j'' = univRestrShape K (univRestrShape K s.1 j') j''
  obtain ⟨a, ha⟩ := s
  cases a with
  | iota k => rfl
  | sigma => rfl
  | pi => rfl
  | termSigma =>
      have hq : (univPshData K).q .termSigma = j := by exact ha
      have hj : j = (1 : Fin 2) := by
        change j = (univPshData K).q .termSigma
        exact hq.symm
      subst hj
      by_cases hj' : j' = (0 : Fin 2)
      · subst hj'
        by_cases hj'' : j'' = (0 : Fin 2)
        · subst hj''
          rfl
        · have hj''1 : j'' = (1 : Fin 2) := by omega
          subst hj''1
          exfalso
          have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom h
          omega
      · have hj'1 : j' = (1 : Fin 2) := by omega
        subst hj'1
        by_cases hj'' : j'' = (0 : Fin 2)
        · subst hj''
          rfl
        · have hj''1 : j'' = (1 : Fin 2) := by omega
          subst hj''1
          rfl
  | termPi =>
      have hq : (univPshData K).q .termPi = j := by exact ha
      have hj : j = (1 : Fin 2) := by
        change j = (univPshData K).q .termPi
        exact hq.symm
      subst hj
      by_cases hj' : j' = (0 : Fin 2)
      · subst hj'
        by_cases hj'' : j'' = (0 : Fin 2)
        · subst hj''
          rfl
        · have hj''1 : j'' = (1 : Fin 2) := by omega
          subst hj''1
          exfalso
          have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom h
          omega
      · have hj'1 : j' = (1 : Fin 2) := by omega
        subst hj'1
        by_cases hj'' : j'' = (0 : Fin 2)
        · subst hj''
          rfl
        · have hj''1 : j'' = (1 : Fin 2) := by omega
          subst hj''1
          rfl

/-- Casting along an equality of a type with itself is the identity. -/
theorem cast_self.{u} {α : Sort u} (e : α = α) (a : α) : cast e a = a := by
  cases e
  rfl

/-- The seven functor laws of `univPsh`. The direction-side laws hold by the
empty and identity cases of `univDirectionRestr`; the shape-side laws by the
definition of `univRestrShape`; and the reindex laws by the definition of
`univReindexDir` and the empty direction types. -/
theorem univPshLaws (K : Type uK) : (univPshData K).IsFunctorial := {
  directionRestr_id := by
    intro a i
    funext d
    by_cases hi : i = (0 : Fin 2)
    · subst hi
      rfl
    · have hi1 : i = (1 : Fin 2) := by omega
      subst hi1
      exact (univDirection_empty K a).elim d
  directionRestr_comp := by
    intro a i i' i'' f g
    funext d
    by_cases hi : i = (0 : Fin 2)
    · subst hi
      by_cases hi' : i' = (0 : Fin 2)
      · subst hi'
        by_cases hi'' : i'' = (0 : Fin 2)
        · subst hi''
          rfl
        · have hi''1 : i'' = (1 : Fin 2) := by omega
          subst hi''1
          exfalso
          have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom g
          omega
      · have hi'1 : i' = (1 : Fin 2) := by omega
        subst hi'1
        exfalso
        have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom f
        omega
    · have hi1 : i = (1 : Fin 2) := by omega
      subst hi1
      exact (univDirection_empty K a).elim d
  shapeRestr_id := univShapeRestr_id_thm K
  shapeRestr_comp := univShapeRestr_comp_thm K
  reindex_naturality := by
    intro j j' g a i i' f
    funext d
    by_cases hi : i = (0 : Fin 2)
    · subst hi
      by_cases hi' : i' = (0 : Fin 2)
      · subst hi'
        rfl
      · have hi'1 : i' = (1 : Fin 2) := by omega
        subst hi'1
        exfalso
        have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom f
        omega
    · have hi1 : i = (1 : Fin 2) := by omega
      subst hi1
      exact (univDirection_empty K (univShapeRestr K g a).1).elim d
  reindex_id := by
    intro j a i b
    by_cases hi : i = (0 : Fin 2)
    · subst hi
      obtain ⟨ashape, ha⟩ := a
      cases ashape with
      | iota k => cases b.1
      | sigma =>
          have hsub : ∀ x y : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (⟨.sigma, ha⟩ : SlicePFunctor.Shape (univSlice K) j).1 (0 : Fin 2), x = y := by
            intro x y
            apply Subtype.ext
            cases x.1; cases y.1; rfl
          exact hsub _ _
      | pi =>
          have hsub : ∀ x y : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (⟨.pi, ha⟩ : SlicePFunctor.Shape (univSlice K) j).1 (0 : Fin 2), x = y := by
            intro x y
            apply Subtype.ext
            cases x.1; cases y.1; rfl
          exact hsub _ _
      | termSigma =>
          have hq : (univPshData K).q .termSigma = j := by exact ha
          have hj : j = (1 : Fin 2) := by
            change j = (univPshData K).q .termSigma
            exact hq.symm
          subst hj
          have e : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (univShapeRestr K (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩).1 0 =
              SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
                (⟨.termSigma, ha⟩ : SlicePFunctor.Shape (univSlice K) (1 : Fin 2)).1 0 :=
            congrArg (fun s : SlicePFunctor.Shape (univSlice K) (1 : Fin 2) ↦
              SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor s.1 0)
              (congrFun (univShapeRestr_id_thm K (1 : Fin 2)) ⟨.termSigma, ha⟩)
          cases e
          apply Subtype.ext
          rfl
      | termPi =>
          have hq : (univPshData K).q .termPi = j := by exact ha
          have hj : j = (1 : Fin 2) := by
            change j = (univPshData K).q .termPi
            exact hq.symm
          subst hj
          have e : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (univShapeRestr K (𝟙 (1 : Fin 2)) ⟨.termPi, ha⟩).1 0 =
              SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
                (⟨.termPi, ha⟩ : SlicePFunctor.Shape (univSlice K) (1 : Fin 2)).1 0 :=
            congrArg (fun s : SlicePFunctor.Shape (univSlice K) (1 : Fin 2) ↦
              SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor s.1 0)
              (congrFun (univShapeRestr_id_thm K (1 : Fin 2)) ⟨.termPi, ha⟩)
          cases e
          apply Subtype.ext
          rfl
    · have hi1 : i = (1 : Fin 2) := by
        omega
      subst hi1
      exact (univDirection_empty K (univShapeRestr K (𝟙 j) a).1).elim b
  reindex_comp := by
    intro j j' j'' g h a i b
    by_cases hi : i = (0 : Fin 2)
    · subst hi
      obtain ⟨ashape, ha⟩ := a
      cases ashape with
      | iota k => cases b.1
      | sigma =>
          have hsub : ∀ x y : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (⟨.sigma, ha⟩ : SlicePFunctor.Shape (univSlice K) j).1 (0 : Fin 2), x = y := by
            intro x y
            apply Subtype.ext
            cases x.1; cases y.1; rfl
          exact hsub _ _
      | pi =>
          have hsub : ∀ x y : SliceDomPFunctor.Direction (univSlice K).toSliceDomPFunctor
              (⟨.pi, ha⟩ : SlicePFunctor.Shape (univSlice K) j).1 (0 : Fin 2), x = y := by
            intro x y
            apply Subtype.ext
            cases x.1; cases y.1; rfl
          exact hsub _ _
      | termSigma =>
          have hq : (univPshData K).q .termSigma = j := by exact ha
          have hj : j = (1 : Fin 2) := by
            change j = (univPshData K).q .termSigma
            exact hq.symm
          subst hj
          have ec : (univPshData K).Direction
              ((univPshData K).shapeRestr (h ≫ g) ⟨.termSigma, ha⟩).1 0 =
              (univPshData K).Direction
                ((univPshData K).shapeRestr h
                  ((univPshData K).shapeRestr g ⟨.termSigma, ha⟩)).1 0 :=
            congrArg (fun s : (univPshData K).toSlicePFunctor.Shape j'' ↦
              (univPshData K).Direction s.1 0)
              (congrFun (univShapeRestr_comp_thm K g h) ⟨.termSigma, ha⟩)
          by_cases hj' : j' = (0 : Fin 2)
          · subst hj'
            by_cases hj'' : j'' = (0 : Fin 2)
            · subst hj''
              change (univPshData K).reindex (h ≫ g) ⟨.termSigma, ha⟩ (i := 0) b =
                  (univPshData K).reindex g ⟨.termSigma, ha⟩ (i := 0)
                    ((univPshData K).reindex h
                      ((univPshData K).shapeRestr g ⟨.termSigma, ha⟩) (i := 0) (cast ec b))
              apply Subtype.ext
              rfl
            · have hj''1 : j'' = (1 : Fin 2) := by omega
              subst hj''1
              exfalso
              have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom h
              omega
          · have hj'1 : j' = (1 : Fin 2) := by omega
            subst hj'1
            by_cases hj'' : j'' = (0 : Fin 2)
            · subst hj''
              change (univPshData K).reindex (h ≫ g) ⟨.termSigma, ha⟩ (i := 0) b =
                  (univPshData K).reindex g ⟨.termSigma, ha⟩ (i := 0)
                    ((univPshData K).reindex h
                      ((univPshData K).shapeRestr g ⟨.termSigma, ha⟩) (i := 0) (cast ec b))
              apply Subtype.ext
              rfl
            · have hj''1 : j'' = (1 : Fin 2) := by omega
              subst hj''1
              have hg : g = 𝟙 (1 : Fin 2) := by
                exact Subsingleton.elim _ _
              have hh : h = 𝟙 (1 : Fin 2) := by
                exact Subsingleton.elim _ _
              rw [hh, hg]
              change (univPshData K).reindex (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩ (i := 0) b =
                  (univPshData K).reindex (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩ (i := 0)
                    ((univPshData K).reindex (𝟙 (1 : Fin 2))
                      ((univPshData K).shapeRestr (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩)
                      (i := 0) (cast _ b))
              apply Subtype.ext
              rfl
      | termPi =>
          have hq : (univPshData K).q .termPi = j := by exact ha
          have hj : j = (1 : Fin 2) := by
            change j = (univPshData K).q .termPi
            exact hq.symm
          subst hj
          have ec : (univPshData K).Direction
              ((univPshData K).shapeRestr (h ≫ g) ⟨.termPi, ha⟩).1 0 =
              (univPshData K).Direction
                ((univPshData K).shapeRestr h
                  ((univPshData K).shapeRestr g ⟨.termPi, ha⟩)).1 0 :=
            congrArg (fun s : (univPshData K).toSlicePFunctor.Shape j'' ↦
              (univPshData K).Direction s.1 0)
              (congrFun (univShapeRestr_comp_thm K g h) ⟨.termPi, ha⟩)
          by_cases hj' : j' = (0 : Fin 2)
          · subst hj'
            by_cases hj'' : j'' = (0 : Fin 2)
            · subst hj''
              change (univPshData K).reindex (h ≫ g) ⟨.termPi, ha⟩ (i := 0) b =
                  (univPshData K).reindex g ⟨.termPi, ha⟩ (i := 0)
                    ((univPshData K).reindex h
                      ((univPshData K).shapeRestr g ⟨.termPi, ha⟩) (i := 0) (cast ec b))
              apply Subtype.ext
              rfl
            · have hj''1 : j'' = (1 : Fin 2) := by omega
              subst hj''1
              exfalso
              have hle : (1 : Fin 2) ≤ (0 : Fin 2) := leOfHom h
              omega
          · have hj'1 : j' = (1 : Fin 2) := by omega
            subst hj'1
            by_cases hj'' : j'' = (0 : Fin 2)
            · subst hj''
              change (univPshData K).reindex (h ≫ g) ⟨.termPi, ha⟩ (i := 0) b =
                  (univPshData K).reindex g ⟨.termPi, ha⟩ (i := 0)
                    ((univPshData K).reindex h
                      ((univPshData K).shapeRestr g ⟨.termPi, ha⟩) (i := 0) (cast ec b))
              apply Subtype.ext
              rfl
            · have hj''1 : j'' = (1 : Fin 2) := by omega
              subst hj''1
              have hg : g = 𝟙 (1 : Fin 2) := by
                exact Subsingleton.elim _ _
              have hh : h = 𝟙 (1 : Fin 2) := by
                exact Subsingleton.elim _ _
              rw [hh, hg]
              change (univPshData K).reindex (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩ (i := 0) b =
                  (univPshData K).reindex (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩ (i := 0)
                    ((univPshData K).reindex (𝟙 (1 : Fin 2))
                      ((univPshData K).shapeRestr (𝟙 (1 : Fin 2)) ⟨.termSigma, ha⟩)
                      (i := 0) (cast _ b))
              apply Subtype.ext
              rfl
    · have hi1 : i = (1 : Fin 2) := by
        omega
      subst hi1
      exact (univDirection_empty K (univShapeRestr K (h ≫ g) a).1).elim b

  }

/-- The presheaf polynomial endofunctor of the universe over the walking
arrow: its W-type is the presheaf inductive-inductive universe, the codes at
fibre `0` and the terms at fibre `1`. -/
def univPsh (K : Type uK) : PresheafPFunctor.{0, 0, uK, 0, 0, 0}
    (Fin 2) (Fin 2) :=
  { toPresheafPFunctorData := univPshData K
    isFunctorial := univPshLaws K }

/-! ## The presheaf initial algebra -/

/-- The W-type of `univPsh`: the presheaf inductive-inductive universe over
the walking arrow. -/
def univW (K : Type uK) : (Fin 2)ᵒᵖ ⥤ Type uK :=
  (univPsh K).W

/-- The codes: the fibre of `univW` over `0`. -/
abbrev Codes (K : Type uK) : Type uK :=
  (univW K).obj ⟨(0 : Fin 2)⟩

/-- The terms: the fibre of `univW` over `1`. -/
abbrev Terms (K : Type uK) : Type uK :=
  (univW K).obj ⟨(1 : Fin 2)⟩

/-- The decoding of a term into its code: the restriction map of the presheaf
`univW` along `0 ⟶ 1`. -/
def fib (K : Type uK) : Terms K → Codes K :=
  (univW K).map waHom.op


/-! ## The constructors -/

/-- The node data of the `iota` code at the starting type `k`: the shape
`.iota k`, whose direction type is empty, so the direction-assignment and both
its compatibility and naturality are vacuous. -/
def iotaNode (K : Type uK) (k : K) :
    ((univPsh K).objPresheaf (univW K)).obj ⟨(0 : Fin 2)⟩ :=
  ⟨⟨⟨⟨(.iota k : univShape K), fun b ↦ PEmpty.elim b⟩,
      (univPsh K).toSliceDomPFunctor.compatible_iff _ (.iota k) _ |>.mpr
        (by intro b; cases b)⟩,
    by
      intro i i' f b
      cases b.1⟩,
    rfl⟩

/-- The `iota` code at the starting type `k`. -/
def univIota (K : Type uK) (k : K) : Codes K :=
  PresheafPFunctor.W.mk (iotaNode K k)

/-- The node data of the `sigma` code with bound code `u`: the shape `.sigma`,
whose single direction is assigned the bound code, the direction-input map
being constantly `0`. -/
def sigmaNode (K : Type uK) (u : Codes K) :
    ((univPsh K).objPresheaf (univW K)).obj ⟨(0 : Fin 2)⟩ :=
  ⟨⟨⟨⟨(.sigma : univShape K), fun _ ↦ ⟨(0 : Fin 2), u⟩⟩,
      (univPsh K).toSliceDomPFunctor.compatible_iff _ .sigma _ |>.mpr
        (by intro b; rfl)⟩,
    by
      intro i i' f b
      have hb : (0 : Fin 2) = i := by
        have hb' : univR K ⟨.sigma, b.1⟩ = i := b.2
        change (0 : Fin 2) = i at hb'
        exact hb'
      subst hb
      have hi' : i' = (0 : Fin 2) := by
        have hle : i' ≤ (0 : Fin 2) := leOfHom f
        omega
      subst hi'
      have hf : f = 𝟙 (0 : Fin 2) := by
        apply Subsingleton.elim
      subst hf
      rw [show (𝟙 (0 : Fin 2)).op = 𝟙 (Opposite.op (0 : Fin 2)) from rfl]
      rw [(univW K).map_id]
      rfl⟩,
    rfl⟩

/-- The `sigma` code with bound code `u`. -/
def univSigma (K : Type uK) (u : Codes K) : Codes K :=
  PresheafPFunctor.W.mk (sigmaNode K u)

/-- The node data of the `pi` code with bound code `u`. -/
def piNode (K : Type uK) (u : Codes K) :
    ((univPsh K).objPresheaf (univW K)).obj ⟨(0 : Fin 2)⟩ :=
  ⟨⟨⟨⟨(.pi : univShape K), fun _ ↦ ⟨(0 : Fin 2), u⟩⟩,
      (univPsh K).toSliceDomPFunctor.compatible_iff _ .pi _ |>.mpr
        (by intro b; rfl)⟩,
    by
      intro i i' f b
      have hb : (0 : Fin 2) = i := by
        have hb' : univR K ⟨.pi, b.1⟩ = i := b.2
        change (0 : Fin 2) = i at hb'
        exact hb'
      subst hb
      have hi' : i' = (0 : Fin 2) := by
        have hle : i' ≤ (0 : Fin 2) := leOfHom f
        omega
      subst hi'
      have hf : f = 𝟙 (0 : Fin 2) := by
        apply Subsingleton.elim
      subst hf
      rw [show (𝟙 (0 : Fin 2)).op = 𝟙 (Opposite.op (0 : Fin 2)) from rfl]
      rw [(univW K).map_id]
      rfl⟩,
    rfl⟩

/-- The `pi` code with bound code `u`. -/
def univPi (K : Type uK) (u : Codes K) : Codes K :=
  PresheafPFunctor.W.mk (piNode K u)

/-- The node data of the `sigma` term at the code `p` with payload `d`: the
shape `.termSigma`, whose two directions are assigned the code and the
payload. -/
def termSigmaNode (K : Type uK) (p d : Codes K) :
    ((univPsh K).objPresheaf (univW K)).obj ⟨(1 : Fin 2)⟩ :=
  ⟨⟨⟨⟨(.termSigma : univShape K),
      fun b ↦ match b with
        | Sum.inl _ => ⟨(0 : Fin 2), p⟩
        | Sum.inr _ => ⟨(0 : Fin 2), d⟩⟩,
      (univPsh K).toSliceDomPFunctor.compatible_iff _ .termSigma _ |>.mpr
        (by intro b; cases b <;> rfl)⟩,
    by
      intro i i' f b
      have hb : (0 : Fin 2) = i := by
        have hb' : univR K ⟨.termSigma, b.1⟩ = i := b.2
        change (0 : Fin 2) = i at hb'
        exact hb'
      subst hb
      have hi' : i' = (0 : Fin 2) := by
        have hle : i' ≤ (0 : Fin 2) := leOfHom f
        omega
      subst hi'
      have hf : f = 𝟙 (0 : Fin 2) := by
        apply Subsingleton.elim
      subst hf
      rw [show (𝟙 (0 : Fin 2)).op = 𝟙 (Opposite.op (0 : Fin 2)) from rfl]
      rw [(univW K).map_id]
      rfl⟩,
    rfl⟩

/-- The `sigma` term at the code `p` with payload `d`. -/
def univTermSigma (K : Type uK) (p d : Codes K) : Terms K :=
  PresheafPFunctor.W.mk (termSigmaNode K p d)

/-- The node data of the `pi` term at the code `p` with payload `d`. -/
def termPiNode (K : Type uK) (p d : Codes K) :
    ((univPsh K).objPresheaf (univW K)).obj ⟨(1 : Fin 2)⟩ :=
  ⟨⟨⟨⟨(.termPi : univShape K),
      fun b ↦ match b with
        | Sum.inl _ => ⟨(0 : Fin 2), p⟩
        | Sum.inr _ => ⟨(0 : Fin 2), d⟩⟩,
      (univPsh K).toSliceDomPFunctor.compatible_iff _ .termPi _ |>.mpr
        (by intro b; cases b <;> rfl)⟩,
    by
      intro i i' f b
      have hb : (0 : Fin 2) = i := by
        have hb' : univR K ⟨.termPi, b.1⟩ = i := b.2
        change (0 : Fin 2) = i at hb'
        exact hb'
      subst hb
      have hi' : i' = (0 : Fin 2) := by
        have hle : i' ≤ (0 : Fin 2) := leOfHom f
        omega
      subst hi'
      have hf : f = 𝟙 (0 : Fin 2) := by
        apply Subsingleton.elim
      subst hf
      rw [show (𝟙 (0 : Fin 2)).op = 𝟙 (Opposite.op (0 : Fin 2)) from rfl]
      rw [(univW K).map_id]
      rfl⟩,
    rfl⟩

/-- The `pi` term at the code `p` with payload `d`. -/
def univTermPi (K : Type uK) (p d : Codes K) : Terms K :=
  PresheafPFunctor.W.mk (termPiNode K p d)

/-! ## Decoding

The decoding of a term into its code is the restriction map `fib`; its
computation on the constructors — `fib (univTermSigma p d) = univSigma p` —
goes through the root-restriction `wRestrTree` of the presheaf W-type and is
deferred to the review this prototype is intended for. The tests exercise the
construction at the level that does compute: the fibres, the constructors, and
the shapes of the constructed codes and terms.
-/
end PresheafIRUniv

end
