/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Mathlib.CategoryTheory.FinCat.Category
public import GebTests.Mathlib.CategoryTheory.FinCat.Basic

/-!
# Tests for the generated mathlib category

Two fixture objects of the category generated by `walkingIso`, at the
default morphism level; five assertions exercising `DecidableEq` on
objects and morphisms, disequality of the fixtures, and the two
category laws at concrete data; and a level-independence pair showing
that the morphism level `v` and the object level `u` of
`FinCat.Obj.category.{v, u}` vary independently.

## Tags

category, finite category, decidable, constructive
-/

@[expose] public section

open CategoryTheory

/-- A source object of the generated category of `walkingIso`. -/
def isoObjSrc : FinCat.Obj.{0} walkingIso := ⟨ULift.up ⟨0, by decide⟩⟩

/-- A target object of the generated category of `walkingIso`. -/
def isoObjTgt : FinCat.Obj.{0} walkingIso := ⟨ULift.up ⟨1, by decide⟩⟩

/-- Assertion 1: object equality is decidable. -/
example : DecidableEq (FinCat.Obj.{0} walkingIso) := inferInstance

/-- Assertion 2: hom equality is decidable, which holds only because
`FinCat.Obj.decidableEqHom` exists — measured to fail (`failed to
synthesize instance`) with that instance removed. -/
example : DecidableEq (isoObjSrc ⟶ isoObjTgt) := inferInstance

/-- Assertion 3: the two fixture objects are distinct. A `DecidableEq`
that accepted everything would still pass assertion 1, so this is the
assertion that separates them. -/
example : isoObjSrc ≠ isoObjTgt := by decide

/-- The forward non-identity morphism of the generated category, at the
fixture objects. -/
def isoObjFwd : isoObjSrc ⟶ isoObjTgt := ULift.up isoFwdMor

/-- The backward non-identity morphism of the generated category, at
the fixture objects. -/
def isoObjBwd : isoObjTgt ⟶ isoObjSrc := ULift.up isoBwdMor

/-- Assertion 4: composing the two non-identity morphisms of
`walkingIso` gives the identity. -/
example : isoObjFwd ≫ isoObjBwd = 𝟙 isoObjSrc := rfl

/-- Assertion 5: the identity is a left unit at a concrete object,
discharged by the category instance's `id_comp` field rather than by
`rfl`, so this checks that the field applies and not merely that the
composite is definitionally the identity. -/
example : 𝟙 isoObjSrc ≫ isoObjFwd = isoObjFwd := Category.id_comp isoObjFwd

/-- A source object of the generated category of `walkingIso`, at
object level `1`. -/
def isoObjSrc1 : FinCat.Obj.{1} walkingIso := ⟨ULift.up ⟨0, by decide⟩⟩

/-- A target object of the generated category of `walkingIso`, at
object level `1`. -/
def isoObjTgt1 : FinCat.Obj.{1} walkingIso := ⟨ULift.up ⟨1, by decide⟩⟩

/-- The forward non-identity morphism of the generated category, at the
level-`1` fixture objects and morphism level `0`. The morphism level is
not determined by the object level of `isoObjSrc1`, so it is stated
against the underlying hom type of `FinCat.Obj.category.{0, 1}` rather
than against `⟶`. -/
def isoObjFwd1 : ULift.{0} (walkingIso.Mor isoObjSrc1.idx.down isoObjTgt1.idx.down) :=
  ULift.up isoFwdMor

/-- The backward non-identity morphism of the generated category, at
the level-`1` fixture objects and morphism level `0`. -/
def isoObjBwd1 : ULift.{0} (walkingIso.Mor isoObjTgt1.idx.down isoObjSrc1.idx.down) :=
  ULift.up isoBwdMor

/-- Level independence: composing the two non-identity morphisms at
object level `1` and morphism level `0` gives the identity of
`FinCat.Obj.category.{0, 1}` — a repeat of assertion 4 at a distinct
object level and an explicitly chosen, independent morphism level.
Written against the parent `CategoryStruct` projection: `≫` and `𝟙`
cannot pin the morphism level through instance search when the object
level does not determine it, and an explicit `@`-argument accepts no
coercion from `Category` to `CategoryStruct`. -/
example :
    @CategoryStruct.comp _ (FinCat.Obj.category.{0, 1} walkingIso).toCategoryStruct
      isoObjSrc1 isoObjTgt1 isoObjSrc1 isoObjFwd1 isoObjBwd1 =
    @CategoryStruct.id _ (FinCat.Obj.category.{0, 1} walkingIso).toCategoryStruct isoObjSrc1 :=
  rfl
