/-
Copyright (c) 2026 Terence Rokop. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Terence Rokop
-/
module

public import Geb.Mathlib.CategoryTheory.FinCat.Hom
public import GebTests.Mathlib.CategoryTheory.FinCat.Basic

/-!
# Tests for functor specifications

Three functor specifications out of the terminal category: the two into
the walking arrow, and the one into the two-element monoid on an
idempotent, which is the only fixture with a two-element hom-set. Five
assertions exercising the two unit laws, the bundled composition check,
and the object and morphism maps of the generated mathlib functor.

The morphism component of each specification is vacuous, the terminal
category having no client morphisms, and the composition check holds
because its quantifier ranges over an empty index type.

## Tags

category, functor, finite category, decidable, constructive
-/

@[expose] public section

/-- The functor specification sending the terminal category's object to
`walkingArrow`'s source. -/
def arrowPointSrc : FinCat.Hom terminalCat walkingArrow where
  objMap := fun _ ↦ arrowSrc
  map := fun _ _ f ↦ f.elim0
  compValid := rfl

/-- The functor specification sending it to the target. -/
def arrowPointTgt : FinCat.Hom terminalCat walkingArrow where
  objMap := fun _ ↦ arrowTgt
  map := fun _ _ f ↦ f.elim0
  compValid := rfl

/-- The functor specification picking out `idemMonoid`'s object. -/
def idemPoint : FinCat.Hom terminalCat idemMonoid where
  objMap := fun _ ↦ idemObj
  map := fun _ _ f ↦ f.elim0
  compValid := rfl

/-- Assertion 1: the identity specification is a left unit at a
concrete specification, by the theorem rather than by `rfl`, so this
checks that the theorem applies and not merely that the two sides are
definitionally equal. -/
theorem arrowPointSrc_id_comp :
    (FinCat.Hom.id terminalCat).comp arrowPointSrc = arrowPointSrc :=
  FinCat.Hom.id_comp arrowPointSrc

/-- Assertion 2: and a right unit, likewise by the theorem. -/
theorem arrowPointSrc_comp_id :
    arrowPointSrc.comp (FinCat.Hom.id walkingArrow) = arrowPointSrc :=
  FinCat.Hom.comp_id arrowPointSrc

/-- Assertion 3: the bundled check agrees with the validity field. -/
theorem arrowPointSrc_compCheck : FinCat.Hom.compCheck arrowPointSrc = true := rfl

/-- The unique object of the category generated by `terminalCat`. -/
def termPoint : FinCat.Obj.{0} terminalCat := ⟨ULift.up termObj⟩

/-- The unique morphism of that category, the reserved identity at its
one object. Stated against the underlying lifted hom type rather than
against `⟶`, which would name the morphism level only through instance
search. -/
def termPointId : ULift.{0} (terminalCat.Mor termObj termObj) :=
  ULift.up (terminalCat.id termObj)

/-- Assertion 4: the generated functor sends the terminal category's one
object to `walkingArrow`'s source. -/
theorem arrowPointSrc_toFunctor_obj :
    (arrowPointSrc.toFunctor.{0, 0}).obj termPoint = ⟨ULift.up arrowSrc⟩ := rfl

/-- Assertion 5: and its one morphism to the reserved identity there. -/
theorem arrowPointSrc_toFunctor_map :
    (arrowPointSrc.toFunctor.{0, 0}).map (X := termPoint) (Y := termPoint) termPointId
      = ULift.up (walkingArrow.id arrowSrc) := rfl
